import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'rw';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, any>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    "sellerRequest.review_submitted": "Review submitted",
  "sellerRequest.thank_you_review": "Thank you for your review!",
  "sellerRequest.failed_to_submit_review": "Failed to submit review",
  "sellerRequest.error": "Error",
  "sellerRequest.write_comment_review": "Please write a comment for your review",
  "sellerRequest.login_to_submit_review": "You must be logged in to submit a review",
  "sellerRequest.loading_reviews": "Loading reviews...",
  "sellerRequest.failed_to_load_reviews": "Failed to load reviews",
  "sellerRequest.customer_reviews": "Customer Reviews",
  "sellerRequest.write_review": "Write a Review",
  "sellerRequest.write_your_review": "Write Your Review",
  "sellerRequest.rating": "Rating",
  "sellerRequest.comment": "Comment",
  "sellerRequest.share_experience": "Share your experience with this product...",
  "sellerRequest.submitting": "Submitting...",
  "sellerRequest.submit_review": "Submit Review",
  "sellerRequest.cancel": "Cancel",
  "sellerRequest.login_to_write_review": "Please {loginLink} to write a review.",
  "auth.login": "Login",
  "sellerRequest.no_reviews_yet": "No reviews yet. Be the first to review this product!",
    "common.home": "Home",
  "common.shop": "Shop",
  "products.product_details": "Product Details",
  "products.rating_reviews": "Rating & Reviews",
  "products.faqs": "FAQs",
    "sellerRequest.search_placeholder": "Search customers by name or email...",
  "sellerRequest.registration_date": "Registration Date",
  "sellerRequest.all_dates": "All Dates",
  "sellerRequest.today": "Today",
  "sellerRequest.this_week": "This Week",
  "sellerRequest.this_month": "This Month",
  "sellerRequest.this_year": "This Year",
  "sellerRequest.number_of_orders": "Number of Orders",
  "sellerRequest.all_orders": "All Orders",
  "sellerRequest.no_orders": "No Orders",
  "sellerRequest.orders_1_5": "1-5 Orders",
  "sellerRequest.orders_6_20": "6-20 Orders",
  "sellerRequest.orders_20_plus": "20+ Orders",
  "sellerRequest.activity": "Activity",
  "sellerRequest.all_activity": "All Activity",
  "sellerRequest.recently_active": "Recently Active",
  "sellerRequest.inactive": "Inactive",
  "sellerRequest.clear_all": "Clear All",
    "vendor_dashboard.title": "Seller Dashboard",
  "vendor_dashboard.add_product": "Add Product",
  "vendor_dashboard.create_order": "Create Order",
  "vendor_dashboard.view_all": "View All",
  "vendor_dashboard.total_orders": "Total Orders",
  "vendor_dashboard.total_revenue": "Total Revenue",
  "vendor_dashboard.total_customers": "Total Customers",
  "vendor_dashboard.total_products": "Total Products",
  "vendor_dashboard.loading": "Loading...",
  "vendor_dashboard.loading_products": "Loading products...",
  "vendor_dashboard.no_products": "No products found.",
  "vendor_dashboard.create_first_product": "Create your first product",
  "vendor_dashboard.revenue_overview": "Revenue Overview",
  "vendor_dashboard.avg_order_value": "Avg. Order Value",
  "vendor_dashboard.no_orders": "No orders found for your products",
  "vendor_dashboard.loading_orders": "Loading orders...",
  "vendor_dashboard.loading_customers": "Loading customers...",
  "vendor_dashboard.no_customers": "No customers found",
  "vendor_dashboard.recent_orders": "Recent Orders",
  "vendor_dashboard.order_id": "Order ID",
  "vendor_dashboard.customer": "Customer",
  "vendor_dashboard.products": "Products",
  "vendor_dashboard.date": "Date",
  "vendor_dashboard.total": "Total",
  "vendor_dashboard.status": "Status",
  "vendor_dashboard.paid": "Paid",
  "vendor_dashboard.pending": "Pending",
  "vendor_dashboard.recent_customers": "Recent Customers",
  "vendor_dashboard.unknown": "Unknown",
  "vendor_dashboard.no_email": "No email",
  "vendor_dashboard.orders_count": "orders",
  "vendor_dashboard.joined": "Joined",
  "vendor_dashboard.my_products": "My Products",
    "admin_filters.search_placeholder": "Search by product name, description...",
  "admin_filters.category": "Category",
  "admin_filters.all_categories": "All Categories",
  "admin_filters.stock": "Stock",
  "admin_filters.all_stock": "All Stock",
  "admin_filters.in_stock": "In Stock",
  "admin_filters.low_stock": "Low Stock (<10)",
  "admin_filters.out_of_stock": "Out of Stock",
  "admin_filters.price_range": "Price Range",
  "admin_filters.all_prices": "All Prices",
  "admin_filters.price_under_10000": "Under 10,000 Rwf",
  "admin_filters.price_between_10000_50000": "10,000 - 50,000 Rwf",
  "admin_filters.price_above_50000": "Above 50,000 Rwf",
  "admin_filters.clear_all": "Clear All",
    "seller_filter.search_by_name": "Search my products by name...",
  "seller_filter.category": "Category",
  "seller_filter.all_categories": "All Categories",
  "seller_filter.stock_level": "Stock Level",
  "seller_filter.all_stock": "All Stock",
  "seller_filter.in_stock": "In Stock (1+)",
  "seller_filter.low_stock": "Low Stock (<10)",
  "seller_filter.critical_stock": "Critical (<5)",
  "seller_filter.out_of_stock": "Out of Stock (0)",
  "seller_filter.performance": "Performance",
  "seller_filter.all_performance": "All Performance",
  "seller_filter.best_selling": "Best Selling",
  "seller_filter.needs_attention": "Needs Attention",
  "seller_filter.new_products": "New Products",
  "seller_filter.clear_all": "Clear All",
    "seller.name": "Product Name *",
  "seller.category": "Category *",
  "seller.select_category": "Select category",
  "seller.price": "Price (Rwf) *",
  "seller.stock": "Stock Quantity *",
  "seller.assign": "Assign to Seller (Optional)",
  "seller.select_seller": "Select seller (leave empty to assign to yourself)",
  "seller.assign_self": "Assign to myself",
  "seller.description": "Description",
  "seller.image_label": "Product Cover Image",
  "seller.upload_image": "Upload Product Image *",
  "seller.or_use_url": "Or choose to use URL *",
  "seller.enter_image_url": "Enter image URL",
  "seller.available_colors": "Available Colors",
  "seller.add_color": "Add color",
  "seller.available_sizes": "Available Sizes",
  "seller.add_size": "Add size",
  "seller.add": "Add",
  "seller.cancel": "Cancel",
  "seller.processing": "Processing...",
  "seller.update_product": "Update Product",
  "seller.create_product": "Create Product",
     "admin.products.title": "All Products",
  "admin.products.my_products": "My Products",
  "admin.products.add_product": "Add Product",
  "admin.products.edit_product": "Edit Product",
  "admin.products.success": "Success",
  "admin.products.error": "Error",
  "admin.products.product_created": "Product created successfully!",
  "admin.products.product_updated": "Product updated successfully!",
  "admin.products.product_deleted": "Product deleted successfully!",
  "admin.products.create_failed": "Failed to create product",
  "admin.products.update_failed": "Failed to update product",
  "admin.products.delete_failed": "Failed to delete product",
  "admin.products.confirm_delete": "Are you sure you want to delete this product?",
    "chat.community_chat": "Community Chat",
  "chat.messages": "messages",
  "chat.vendors_and_admins": "Vendors & Admins",
  "chat.no_messages_yet": "No messages yet. Start the conversation!",
  "chat.failed_load": "Failed to load chat",
  "chat.retry": "Retry",
  "chat.failed_send_message": "Failed to send message",
  "chat.type_message_placeholder": "Type a message...",
  "chat.characters": "characters",
    "customers": {
    "loading_users": "Loading users...",
    "failed_load_users": "Failed to load users.",
    "user_management": "User Management",
    "search_users": "Search users...",
    "total_buyers": "Total Buyers",
    "total_sellers": "Total Sellers",
    "total_users": "Total Users",
    "all_users": "All Users",
    "user": "User",
    "email": "Email",
    "status": "Status",
    "joined": "Joined",
    "active": "Active",
    "inactive": "Inactive",
    "failed_to_update": "Failed to update user"
  },
  "vendors": {
    "admin": "Admin",
    "seller": "Seller",
    "buyer": "Buyer"
  },
    "customer_management.title": "Customer Management ({{count}})",
  "customer_management.customer": "Customer",
  "customer_management.contact": "Contact",
  "customer_management.orders": "Orders",
  "customer_management.joined": "Joined",
  "customer_management.actions": "Actions",
  "customer_management.id_prefix": "ID",
  "customer_management.orders_label": "orders",
  "customer_management.no_customers": "No customers found",
  "customer_management.no_customers_subtext": "Customers will appear here when they purchase your products",
  "customer_management.success": "Success",
  "customer_management.customer_updated": "Customer updated successfully",
  "customer_management.error": "Error",
  "customer_management.update_failed": "Failed to update customer",
  "customer_management.customer_removed": "Customer removed successfully",
  "customer_management.remove_failed": "Failed to remove customer",
  "customer_management.confirm_delete": "Are you sure you want to remove this customer? This will not delete their account but remove them from your customer list.",
  "customer_management.loading_customers": "Loading customers...",
  "customer_management.edit_customer": "Edit Customer",
  "customer_management.name": "Name",
  "customer_management.email": "Email",
  "customer_management.phone": "Phone",
  "customer_management.address": "Address",
  "customer_management.cancel": "Cancel",
  "customer_management.updating": "Updating...",
  "customer_management.update_customer": "Update Customer",
     "seller_customers.failed_load_customers": "Failed to load customers",
  "seller_customers.my_customers": "My Customers",
  "seller_customers.total_customers": "Total: {{count}} customers",
  "seller_customers.total_customers_label": "Total Customers",
  "seller_customers.total_orders_label": "Total Orders",
  "seller_customers.new_this_month_label": "New This Month",
    "seller_permissions.manage_seller_permissions": "Manage Seller Permissions",
  "seller_permissions.permissions_updated_title": "Permissions Updated",
  "seller_permissions.permissions_updated_description": "Seller permissions have been updated successfully",
  "seller_permissions.error_title": "Error",
  "seller_permissions.error_description": "Failed to update permissions",
  "seller_permissions.status.active": "Active",
  "seller_permissions.status.inactive": "Inactive",
  "seller_permissions.business": "Business",
  "seller_permissions.order_management_permissions": "Order Management Permissions",
  "seller_permissions.confirm_orders": "Confirm Orders",
  "seller_permissions.allow_confirm_payment": "Allow seller to confirm payment status",
  "seller_permissions.edit_orders": "Edit Orders",
  "seller_permissions.allow_edit_order": "Allow seller to modify order details",
  "seller_permissions.cancel_orders": "Cancel Orders",
  "seller_permissions.allow_cancel_order": "Allow seller to cancel orders",
  "seller_permissions.delete_orders": "Delete Orders",
  "seller_permissions.allow_delete_order": "Allow seller to permanently delete orders",
  "seller_permissions.customer_management_permissions": "Customer Management Permissions",
  "seller_permissions.create_customers": "Create New Customers",
  "seller_permissions.allow_add_customers": "Allow seller to add new customers when creating orders",
  "seller_permissions.cancel": "Cancel",
  "seller_permissions.saving": "Saving...",
  "seller_permissions.save_permissions": "Save Permissions",
    "common.loading": "Loading...",
  "common.success": "Success",
  "common.error": "Error",
  "common.creating": "Creating...",
  "common.cancel": "Cancel",

  "seller_management.heading": "Seller Management",
  "seller_management.add_button": "Add Seller",
  "seller_management.new_seller": "New Seller",
  "seller_management.name_required": "Name required",
  "seller_management.label_name": "Full Name",
  "seller_management.placeholder_name": "John Doe",
  "seller_management.email_required": "Email required",
  "seller_management.email_invalid": "Invalid email address",
  "seller_management.label_email": "Email Address",
  "seller_management.password_required": "Password required",
  "seller_management.password_min_length": "Minimum 6 characters",
  "seller_management.label_password": "Password",
  "seller_management.create": "Create Seller",
  "seller_management.created_success": "Seller created successfully",
  "seller_management.create_error": "Failed to create seller",
  "seller_management.status_updated": "Seller status updated",
  "seller_management.status_update_error": "Error updating seller status",
  "seller_management.load_error": "Failed to load sellers",

  "seller_management.count_all": "Total Sellers",
  "seller_management.count_active": "Active",
  "seller_management.count_pending": "Pending",
  "seller_management.count_suspended": "Suspended",
  "seller_management.active_filter": "Active Filter",

  "seller_management.search_placeholder": "Search sellers...",

  "seller_management.all_sellers": "All Sellers",

  "seller_management.col_seller": "Seller",
  "seller_management.col_business": "Business",
  "seller_management.col_contact": "Contact",
  "seller_management.col_status": "Status",
  "seller_management.col_joined": "Joined",
  "seller_management.col_actions": "Actions",

  "seller_management.status_active": "Active",
  "seller_management.status_suspended": "Suspended",
  "seller_management.status_pending": "Pending",
  "seller_management.status_inactive": "Inactive",

  "seller_management.approve": "Approve",
  "seller_management.suspend": "Suspend",
  "seller_management.permissions": "Permissions",
  "seller_management.reactivate": "Reactivate",

  "seller_management.no_results_search": "No sellers found matching \"{{term}}\"",
  "seller_management.no_results": "No sellers found",
    "user_filters.search_placeholder": "Search users by name, email, or phone...",
  "user_filters.status": "Status",
  "user_filters.all_status": "All Status",
  "user_filters.active": "Active",
  "user_filters.inactive": "Inactive",
  "user_filters.blocked": "Blocked",
  "user_filters.role": "Role",
  "user_filters.all_roles": "All Roles",
  "user_filters.buyers": "Buyers",
  "user_filters.sellers": "Sellers",
  "user_filters.admins": "Admins",
  "user_filters.registered": "Registered",
  "user_filters.all_dates": "All Dates",
  "user_filters.today": "Today",
  "user_filters.this_week": "This Week",
  "user_filters.this_month": "This Month",
  "user_filters.this_year": "This Year",
  "user_filters.clear_all": "Clear All",
    // Navigation
    'Personal.Information':'Personal Information',
    'Full.Name':'Full name',
    'Email':'Email',
    'Phone':'Telephone',
    'Address':'Address',
    'Business.Information':'Business Information',
    'Business.Name':'Business Name',
    'Business.Category':'Business Category',
    'Business.Location':'Business Location',
    'Success':'success',
    'Profile.updated.successfully':'Profile updated successfully',
    'Failed.to.update.profile':'Failed to update profile',
    'Business.Website':'Business Website',
    'Business.Description':'Business Description',
    'Updating...':'Updating...',
    'Update.Profile':'Update Profile',
    'Account.Details':'Account Details',
    "seller_request.back_to_home": "Back to Home",
    "seller_request.become_seller": "Become a Seller",
    "seller_request.have_account": "Already have an account?",
    "seller_request.full_name": "Full Name",
    "seller_request.phone": "Phone Number",
    "seller_request.email": "Email Address",
    "seller_request.business_name": "Business Name",
    "seller_request.gender": "Gender",
    "seller_request.male": "Male",
    "seller_request.female": "Female",
    "seller_request.other": "Other",
    "seller_request.prefer_not": "Prefer not to say",
    "seller_request.password": "Password",
    "seller_request.agree_text": "I have read the",
    "seller_request.terms": "Terms and Conditions",
    "seller_request.submit": "Submit Request",
    "seller_request.submitting": "Submitting...",
    "seller_request.error": "Error",
    "seller_request.accept_terms": "Please accept the terms and conditions",
    "seller_request.success_title": "Success!",
    "seller_request.success_message": "Your seller request has been submitted. You will be notified once approved by an admin.",
    "seller_request.redirect_message": "Please login with your credentials once your seller account is approved.",
    "seller_request.request_submitted": "Request Submitted!",
    "seller_request.await_email": "Your seller account request has been submitted successfully. You'll receive an email notification once an admin approves your account.",
    "seller_request.redirecting_login": "Redirecting to login page in a few seconds...",
    "seller_request.submit_failed": "Failed to submit seller request",

    'nav.home': 'Home',
    'Search.products':'Search Products',
    'Category':'Category',
    'All.Categories':'All Categories',
    'Price.Range':'Price Range',
    'Min':'Min',
    'Max':'Max',
    'Apply.Price':'Apply Price',
    'Created.Date':'Created Date',
    'All.Dates':'All Dates',
    'Today':'Today',
    'This.Week':'This Week',
    'This.Month':'This Month',
    'Custom.Range':'Custom Range',
    'Apply.Range':'Apply Range',
    'Clear.All':'Clear All',
    'nav.products': 'Products',
    'nav.categories': 'Categories',
    'Total.Revenue':'Total Revenue',
    'Total.Orders':'Total Orders',
    'nav.about': 'About',
    'Loading.reports': 'Loading reports',
    'My.Business.Summary': 'My Business Summary',
    'Failed.Actions.Dashboard':'Failed Actions Dashboard',
    'Order.Issues':'Order isssues',
    'Authentication.Issues':'Authentication Issues',
    'Email.Issues':'Email Issues',
    'Error':'ikosa',
    'Please.fill':'Please fill in all required fields',
    'Email.confirmation':'Email is required for confirmation',
    'checkout.street_line': 'Street Line',
    'checkout.order_placed_success': 'Order placed successfully! Check your email for confirmation.',
    'Order.Completed!':'Order Completed!',
    'Continue.Shopping':'Continue Shopping',
    'Order.Summary':'Order Summary',

    'Cart.Issues':'Cart Issues',
    'Chart.Issues':'Chart Issues',
    'Vendor.Issues':'Vendor Issues',
    'Database.Summary': 'Database Summary',
    'Don.have':'Dont have account ?',
    'Monthly.Revenue': 'Monthly Revenue',
    'My.Products': 'My Products',
    'My.Orders': 'My Orders',
    'Order.Analytics':'Order Analytics',
    'Product.Analytics': 'Product Analytics',
    'Subtotal':'Subtotal',
    'nav.contact': 'Contact',
    'Delivery.Fee':'Delivery Fee',
    'Paid.on.Delivery':'Paid on Delivery',
    'delivery.fee.delivery':'delivery fee to be paid on delivery',
    'Vendor.Performance':'Vendor Performance',
    'Report.Analytics':'Report Analytics',
    'Customer.Analytics': 'Customer Analytics',
    'Our.Products': 'Our Products',
    'Sign.Up': 'Sign Up',
    'My.Sales.Overview':'My sale Overview',
    'Sales.Overview':'Sales Overview',
    'forget': 'Forgot Password?',
    'nav.dashboard': 'Dashboard',
    'seller.management':' Seller Management',
    'Next': 'Next',
    'Previous': 'Previous',
    'Available:': 'Available:',
    'clear.all': 'Clear All Filters',
    'Try.adjusting': 'Try adjusting your search or filter criteria',
    'No.product': 'No products found',
    'search':'Search',
    'Showing': 'Showing',
    'category.search': 'Category',
    'Add.Seller': 'Add Seller',
    'Discover.our': 'Discover our amazing collection of products',
    // Common
    'common.welcome': 'Welcome',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.clear': 'Clear',
    'common.submit': 'Submit',
    'common.close': 'Close',
    'common.open': 'Open',
    'common.view': 'View',
    
    // Authentication
    'auth.register': 'Register',
    'auth.logout': 'Logout',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.name': 'Name',
    'auth.login_required': 'Login Required',
    'auth.login_to_add_cart': 'Please login to add items to cart',
    'auth.forgot_password': 'Forgot Password?',
    'auth.remember_me': 'Remember me',
    'auth.dont_have_account': "Don't have an account?",
    'auth.already_have_account': 'Already have an account?',
    'auth.sign_up': 'Sign up',
    'auth.sign_in': 'Sign in',
    'auth.user_found': 'User found!',
    'auth.user_not_found': 'User not found',
    'auth.no_account_found': 'No account found with this email address',
    'auth.verification_code_sent': 'A verification code has been sent to your email',
    'auth.enter_email_check': 'Enter your email address to check if an account exists',
    'auth.enter_verification_code': 'Enter the verification code sent to your email',
    'auth.account_verified': 'Account verified! Click below to reset your password',
    'auth.verification_code': 'Verification Code',
    'auth.enter_code': 'Enter 6-digit code',
    'auth.verify_code': 'Verify Code',
    'auth.verifying': 'Verifying...',
    'auth.checking': 'Checking...',
    'auth.check_email': 'Check Email',
    'auth.enter_email': 'Enter your email',
    'auth.account_found': 'Account Found',
    'auth.reset_password': 'Reset Password',
    'auth.code_verified': 'Code verified!',
    'auth.can_reset_password': 'You can now reset your password',
    'auth.invalid_code': 'Invalid code',
    'auth.code_incorrect': 'The verification code is incorrect or expired',
    'auth.failed_check_user': 'Failed to check user existence',
    'auth.failed_verify_code': 'Failed to verify code',
    'common.back': 'Back',
    
    // Products
    'products.search_placeholder': 'Search for products...',
    'products.no_products_available': 'No products available at the moment.',
    'products.view_more': 'View More',
    'products.loading_related': 'Loading related products...',
    'products.you_might_like': 'You might also like',
    'products.add_to_cart': 'Add to Cart',
    'products.out_of_stock': 'Out of Stock',
    'products.in_stock': 'In Stock',
    
    // Cart
    'cart.added_to_cart': 'Added to cart',
    'cart.item_added': '{{item}} has been added to your cart.',
    'cart.failed_to_add': 'Failed to add to cart',
    'cart.add_to_cart': 'Add to Cart',
    'cart.adding': 'Adding...',
    
    // Categories - FIXED MISSING TRANSLATIONS
    'categories.loading': 'Loading categories...',
    'categories.no_categories': 'No categories available.',
    'categories.browse_categories': 'BROWSE BY CATEGORIES',
    'categories.discover_products': 'Discover our wide range of products organized by category',
    'categories.view_all': 'View All Categories',
    
    // Home
    'home.new_arrivals': 'NEW ARRIVALS',
    'home.top_selling': 'TOP SELLING',
    'home.browse_categories': 'Browse by Category',
    
    // Hero Section
    'hero.title': 'Welcome to A Smart Marketplace for Women Entrepreneurs in Rwanda',
    'hero.description': 'Built for women entrepreneurs in Kigali, WomXchange Rwanda provides a seamless online platform for selling, managing, and expanding your business.',
    'hero.shop_now': 'Shop Now',
    'hero.image_alt': 'Successful woman entrepreneur',
    
    // Footer
    'footer.company_name': 'WomXchange Rwanda',
    'footer.company_description': 'Empowering women entrepreneurs across Rwanda with a smart marketplace platform.',
    'footer.location': 'Kigali, Rwanda',
    'footer.quick_links': 'Quick Links',
    'footer.support': 'Support',
    'footer.help_center': 'Help Center',
    'footer.shipping_info': 'Shipping Info',
    'footer.returns': 'Returns',
    'footer.privacy_policy': 'Privacy Policy',
    'footer.terms_of_service': 'Terms of Service',
    'footer.location_title': 'Location',
    'footer.location_description': 'Visit our office in Kigali or shop online from anywhere in Rwanda.',
    'footer.store_hours': 'Store Hours',
    'footer.weekdays': 'Mon - Fri: 9:00 AM - 9:00 PM',
    'footer.weekends': 'Sat - Sun: 10:00 AM - 9:00 PM',
    'footer.copyright': '© 2024 WomXchange. All rights reserved women entrepreneurs.',
    
    // Testimonials
    'testimonials.title': 'OUR HAPPY CUSTOMERS',
    'testimonials.review_1': 'Amazing quality products and fast delivery. I love supporting local women entrepreneurs!',
    'testimonials.review_2': 'The cosmetics I bought are incredible. Great prices and authentic products from talented women.',
    'testimonials.review_3': 'This marketplace changed my shopping experience. So many unique items and great customer service!',
    'testimonials.review_4': 'Excellent customer service and high quality products. Will definitely shop here again!',
    'testimonials.review_5': 'Love the variety of products available. Supporting local businesses has never been easier!',
    
    // Banner
    'banner.sell_on_system': 'Sell on Our System',
    'banner.join_as_seller': 'Join as a Seller',
    
    // Dashboard
    'dashboard.notifications': 'No notifications',
    'dashboard.profile': 'Profile',
    'dashboard.settings': 'Settings',
    
    // Error Pages
    'error.404.title': '404 - Page Not Found',
    'error.404.message': 'The page you are looking for does not exist.',
    'error.404.return_home': 'Return to Home',
    'error.failed_load_products': 'Failed to load products',
    
    // Language
    'language.english': 'English',
    'language.kinyarwanda': 'Kinyarwanda',
    
    // Navigation Additional
    'nav.sellers': 'Sellers',
    'nav.back_to_home': 'Back to Home',
    
    // Modal and Dialog Messages
    'modal.password_error': 'Password Error',
    'modal.passwords_not_match': "Passwords don't match or are empty",
    'modal.registration_successful': 'Registration Successful!',
    'modal.account_created': 'Account created. Now placing your order...',
    'modal.registration_failed': 'Registration Failed',
    'modal.failed_create_account': 'Failed to create account',
    'modal.order_placed_success': 'Order Placed Successfully!',
    'modal.order_confirmation_sent': 'Your order has been placed and confirmation email sent.',
    'modal.order_failed': 'Order Failed',
    'modal.failed_place_order': 'Failed to place order',
    'modal.create_account_optional': 'Create Account (Optional)',
    'modal.place_order': 'Place Order',
    'modal.create_account_benefits': 'Create an account to track your orders and get exclusive offers, or skip to place order as guest.',
    'modal.create_account': 'Create account',
    'modal.skip_place_order': 'Skip & Place Order',
    'modal.account_created_success': 'Account created successfully! Now placing your order...',
    
    // Contact Page Messages
    'contact.message_sent_success': 'Your message has been sent successfully!',
    'contact.message_send_failed': 'Failed to send message. Please try again later.',
    'contact.error_occurred': 'An error occurred. Please try again.',
    
    // Register Page
    'register.back_to_home': 'Back to Home',
    'register.create_account': 'Create Account',
    'register.already_have_account': 'Already have an account?',
    'register.creating_account': 'Creating Account...',
    
    // Register Page Additional
    'register.registration_successful': 'Registration successful',
    'register.login_with_credentials': 'Please login with your credentials',
    'register.registration_failed': 'Registration failed',
    'register.something_went_wrong': 'Something went wrong',
    'register.full_name': 'Full Name',
    'register.enter_full_name': 'Enter your full name',
    'register.email': 'Email',
    'register.enter_email': 'Enter your email',
    'register.password': 'Password',
    'register.create_password': 'Create a password',
    'register.account_type': 'Account Type',
    'register.select_account_type': 'Select account type',
    'register.buyer': 'Buyer',
    'register.seller': 'Seller',
    'register.admin': 'Admin',
    'register.looking_to_sell': 'Looking to sell products?',
    'register.start_selling_now': 'Start Selling Now',
    
    // Chat Interface
    'chat.messages_vendors_admins': 'messages • Vendors & Admins',
    'chat.failed_to_load': 'Failed to load chat',
    'chat.type_message': 'Type a message...',
    
    // Admin Pages
    'admin.user': 'Users',
    'admin.vendors': 'Sellers',
    'admin.products': 'Products',
    'admin.orders': 'Orders',
    'admin.reports': 'Reports',
    'admin.analytics': 'Analytics',
    'admin.community_chat': 'Community Chat',
    'admin.management': 'Management',
    'admin.sidebar.dashboard': 'Dashboard',
    'admin.sidebar.customers': 'Customers',
    'admin.sidebar.vendors': 'Vendors',
    'admin.sidebar.products': 'Products',
    'admin.sidebar.orders': 'Orders',
    'admin.sidebar.reports': 'Reports',
    'admin.sidebar.analytics': 'Category',
    'admin.sidebar.profile': 'Profile',
    'admin.sidebar.settings': 'Settings',
    
    // Customer Management
    'customers.title': 'Customers Management',
    'customers.add_customer': 'Add Customer',
    'customers.search_customers': 'Search customers...',
    'customers.all_customers': 'All Customers',
    // 'customers.active': 'Active', // Removed duplicate
    'customers.inactive': 'Inactive',
    'customers.total_customers': 'Total Customers',
    'customers.customer': 'Customer',
    'customers.email': 'Email',
    'customers.joined': 'Joined',
    'customers.status': 'Status',
    'customers.actions': 'Actions',
    'customers.no_customers': 'No customers found',
    'customers.import': 'Import',
    'customers.export': 'Export',
    
    // Vendor Management
    'vendors.title': 'Vendors Management',
    'vendors.add_vendor': 'Add Vendor',
    'vendors.search_vendors': 'Search vendors...',
    'vendors.total_vendors': 'Total Vendors',
    'vendors.total_users': 'Total Users',
    'vendors.vendor': 'Vendor',
    'vendors.role': 'Role',
    'vendors.no_vendors': 'No vendors found',
    'vendors.active_sellers': 'Active SELLERs',
    'vendors.all_registered': 'All registered users',
    
    // Orders Management
    'orders.title': 'Orders Management',
    'orders.refresh': 'Refresh Orders',
    'orders.search_orders': 'Search orders...',
    'orders.total_orders': 'Total Orders',
    'orders.paid_orders': 'Paid Orders',
    'orders.pending_payment': 'Pending Payment',
    'orders.total_revenue': 'Total Revenue',
    'orders.order_id': 'Order ID',
    'orders.customer': 'Customer',
    'orders.total_price': 'Total Price',
    'orders.payment_status': 'Payment Status',
    'orders.delivery_status': 'Delivery Status',
    'orders.date': 'Date',
    'orders.actions': 'Actions',
    'orders.confirm_payment': 'Confirm Payment',
    'orders.mark_delivered': 'Mark Delivered',
    'orders.no_orders': 'No orders found',
    'orders.confirmed_by_admin': 'Confirmed by Admin',
    'orders.awaiting_admin': 'Awaiting Admin Confirmation',
    'orders.payment_code_generated': 'Payment Code Generated',
    'orders.pending_payment_status': 'Pending Payment',
    'orders.delivered': 'Delivered',
    'orders.not_delivered': 'Not Delivered',
    
    // User Pages
    'categories.title': 'Shop by Categories',
    'categories.description': 'Discover our wide range of product categories and find exactly what you\'re looking for.',
    'categories.no_categories_found': 'No Categories Found',
    'categories.categories_appear': 'Categories will appear here once they are added to the system.',
    
    // Products Page
    'products.title': 'Products',
    'products.filters': 'Filters',
    'products.search': 'Search',
    'products.category': 'Category',
    'products.price_range': 'Price Range',
    'products.clear_filters': 'Clear Filters',
    'products.showing_results': 'Showing {{count}} of {{total}} products',
    'products.no_products_matching': 'No products found matching your filters.',
    'products.previous': 'Previous',
    'products.next': 'Next',
    
    // Cart Page
    'cart.title': 'YOUR CART',
    'cart.empty': 'Your cart is empty',
    'cart.continue_shopping': 'Continue Shopping',
    'cart.order_summary': 'Order Summary',
    'cart.subtotal': 'Subtotal',
    'cart.discount': 'Discount (-2%)',
    'cart.delivery_fee': 'Delivery Fee',
    'cart.total': 'Total',
    'cart.go_to_checkout': 'Go to checkout',
    'cart.please_login': 'Please Login',
    'cart.login_to_view': 'You need to be logged in to view your cart.',
    'cart.loading': 'Loading cart...',
    
    // Checkout Page
    'checkout.title': 'Checkout',
    'checkout.billing_info': 'Billing Information',
    'checkout.full_name': 'Full Name',
    'checkout.email': 'Email',
    'checkout.phone': 'Phone Number',
    'checkout.country_code': 'Country Code',
    'checkout.enter_phone': 'Enter phone number',
    'checkout.address': 'Address',
    'checkout.city': 'City',
    'checkout.payment_method': 'Payment Method',
    'checkout.mobile_money': 'Mobile Money',
    'checkout.place_order': 'Place Order',
    'checkout.order_summary': 'Order Summary',
    
    // Dashboard & Sidebar
    'sidebar.dashboard': 'Dashboard',
    'sidebar.customers': 'Customers',
    'sidebar.vendors': 'Sellers', 
    'sidebar.products': 'Products',
    'sidebar.orders': 'Orders',
    'sidebar.reports': 'Reports',
    'sidebar.analytics': 'Analytics',
    'sidebar.profile': 'Profile',
    'sidebar.settings': 'Settings',
    'sidebar.community_chat': 'Community Chat',
    'sidebar.management': 'Management',
    
    // Order Complete Page
    'order_complete.title': 'Order Placed Successfully!',
    'order_complete.message': 'Your order has been received and is being processed.',
    'order_complete.order_id': 'Order ID: #{{id}}',
    'order_complete.payment_processing': 'Payment Processing',
    'order_complete.generate_code': 'Generate a payment code to proceed with MoMo payment',
    'order_complete.generate_payment_code': 'Generate Payment Code',
    'order_complete.payment_code': 'Your Payment Code:',
    'order_complete.use_code': 'Use this code to complete your MoMo payment, then confirm below',
    'order_complete.made_payment': 'I\'ve Made the Payment',
    'order_complete.awaiting_confirmation': 'Awaiting Admin Confirmation',
    'order_complete.payment_verification': 'Your payment is being verified by our admin team',
    'order_complete.view_orders': 'View My Orders',
    'order_complete.return_home': 'Return to Home Page',
    'order_complete.secured': 'Your purchases are secured by industry-standard encryption',
    'order_complete.order_id_not_found': 'Order ID not found',
    'order_complete.code_generated_success': 'Payment code generated successfully',
    'order_complete.failed_generate_code': 'Failed to generate payment code',
    'order_complete.payment_confirmed': 'Payment confirmed! Awaiting admin verification.',
    'order_complete.failed_confirm_payment': 'Failed to confirm payment',
    "title": "Products Management",
    "add_product": "Add Product",
    "edit_product": "Edit Product",
    "create_product": "Create New Product",
    "created": "Product created successfully.",
    "updated": "Product updated successfully.",
    "deleted": "Product deleted successfully.",
    "create_failed": "Failed to create product.",
    "update_failed": "Failed to update product.",
    "delete_failed": "Failed to delete product.",
    "load_error": "Failed to load products.",
    "confirm_delete": "Are you sure you want to delete this product?",
    "name": "Name",
    "description": "Description",
    "price": "Price (Rwf)",
    "stock": "Stock",
    "image": "Image URL",
    "category": "Category",
    "select_category": "Select a category",
    "create": "Create",
    "update": "Update",
    "all": "All Products",
    "actions": "Actions",
    "no_products": "No products found",
    //Dashboard
    'dashboard.daily_sales': 'Daily Sales',
    'dashboard.daily_users': 'Daily user',
    'dashboard.summary_sales': 'Summary sales',
    'dashboard.chart_placeholder': 'Chart visualization area',
    'dashboard.upcoming_payments': 'Upcoming Payments',
    'dashboard.payment_data': 'Payment data',
    'dashboard.recent_orders': 'Recent Orders',
    'dashboard.id': 'Id',
    'dashboard.customer_name': 'Customer Name',
    'dashboard.product_name': 'Product Name',
    'dashboard.price': 'Price',
    'dashboard.picture': 'Picture',
    'dashboard.sample_product': 'Shirt',
    'dashboard.expense_status': 'Expense status',
    'dashboard.vendor_role': 'Vendor',
    'dashboard.retry': 'Retry',
    
    // Failed Actions
    'failed_actions.title': 'Failed Actions Management',
    'failed_actions.description': 'Monitor and resolve system failures',
    'failed_actions.type': 'Type',
    'failed_actions.status': 'Status',
    'failed_actions.reason': 'Reason',
    'failed_actions.date': 'Date',
    'failed_actions.actions': 'Actions',
    'failed_actions.resend': 'Resend',
    'failed_actions.retry': 'Retry',
    'failed_actions.clear': 'Clear',
    'failed_actions.resolve': 'Resolve',
    'failed_actions.failed_email': 'Email Failed',
    'failed_actions.failed_login': 'Login Failed',
    'failed_actions.failed_cart': 'Cart Operation Failed',
    'failed_actions.failed_chat': 'Chat Failed',
    'failed_actions.failed_vendor': 'Vendor Operation Failed',
    'failed_actions.failed_order': 'Order Failed',
    'failed_actions.no_actions': 'No failed actions found',
    'failed_actions.refreshing': 'Refreshing...',
    'failed_actions.loading': 'Loading failed actions...',
    
    // Filters
    'filters.search': 'Search',
    'filters.category': 'Category',
    'filters.date_range': 'Date Range',
    'filters.price_range': 'Price Range',
    'filters.stock_range': 'Stock Range',
    'filters.status': 'Status',
    'filters.clear_all': 'Clear All',
    'filters.apply': 'Apply Filters',
    'filters.start_date': 'Start Date',
    'filters.end_date': 'End Date',
    'filters.min_price': 'Min Price',
    'filters.max_price': 'Max Price',
    'filters.min_stock': 'Min Stock',
    'filters.max_stock': 'Max Stock',
    
    // About Page
    'about.our_story': 'Our Story',
    'about.story_content': 'Founded in the heart of Kigali, wXc, WomXchange was born from a simple but powerful idea: to create an online marketplace where Rwandan women would showcase, sell, and grow their businesses on their own terms. What began as individual idea now has become initiative among women entrepreneurs and it has blossomed into Rwanda\'s premier e-commerce platform dedicated to elevating women entrepreneurs across every Kigali.',
    'about.mission': 'Mission',
    'about.mission_content': 'Founded in the heart of Kigali, wXc, WomenXchange was born from a simple but powerful idea to create an online marketplace where Rwandan women could showcase, sell, and grow their businesses on their own terms. What began as individual idea now has become initiative among women entrepreneurs and it has blossomed into Rwanda\'s premier e-commerce platform dedicated to elevating women entrepreneurs across every Kigali.',
    'about.vision': 'Vision',
    'about.vision_content': 'Founded in the heart of Kigali, wXc, WomenXchange was born from a simple but powerful idea to create an online marketplace where Rwandan women could showcase, sell, and grow their businesses on their own terms. What began as individual idea now has become initiative among women entrepreneurs and it has blossomed into Rwanda\'s premier e-commerce platform dedicated to elevating women entrepreneurs across every Kigali.',
    
    // Dashboard Additional
    'dashboard.total_revenue': 'Total Revenue',
    'dashboard.paid_revenue': 'Paid Revenue',
    'dashboard.total_orders': 'Total Orders',
    'dashboard.total_users': 'Total Users',
    'dashboard.products': 'Products',
    'dashboard.buyers': 'Buyers',
    'dashboard.sellers': 'Sellers',
    'dashboard.admins': 'Admins',
    'dashboard.monthly_orders': 'Monthly Orders',
    'dashboard.user_roles_distribution': 'User Roles Distribution',
    'dashboard.monthly_revenue_trend': 'Monthly Revenue Trend',
    'dashboard.payment_status': 'Payment Status',
    'dashboard.payment_summary': 'Payment Summary',
    'dashboard.paid_orders': 'Paid Orders',
    'dashboard.pending': 'Pending',
    'dashboard.order_statistics': 'Order Statistics',
    'dashboard.pending_orders': 'Pending Orders',
    'dashboard.user_statistics': 'User Statistics',
    'orders.paid': 'Paid',
    'orders.processing': 'Processing',
    
    // Contact Page
    'contact.send_message': 'Send Us a Message',
    'contact.full_name': 'Enter your full name',
    'contact.email': 'Enter your email',
    'contact.message': 'Enter your message here...',
    'contact.send': 'Send',
    'contact.phone': 'Phone:',
    'contact.email_label': 'Email:',
    'contact.times': 'Times:',
    'contact.location': 'Location:',
    'contact.hours': 'Mon - Sun: 7 AM - 9 PM',
    'contact.address': 'Downtown House Kigali',
    
    // Analytics
    'analytics.title': 'Analytics',
    'analytics.coming_soon': 'Analytics page coming soon...',
    
    // Checkout
    'checkout.back_to_cart': 'Back to Cart',
    'checkout.empty_cart': 'Your cart is empty',
    'checkout.continue_shopping': 'Continue Shopping',
    'checkout.customer_information': 'Customer Information',
    'checkout.first_name': 'First Name *',
    'checkout.last_name': 'Last Name *',
    'checkout.email_required': 'Email *',
    'checkout.phone_number': 'Phone Number',
    'checkout.location_required': 'Location *',
    'checkout.billing_address': 'Billing Address',
    'checkout.city_required': 'City *',
    'checkout.state_required': 'State/Province *',
    'checkout.postal_code': 'Postal Code *',
    'checkout.country_required': 'Country *',
    'checkout.shipping_address': 'Shipping Address',
    'checkout.same_as_customer': 'Same as customer address',
    'checkout.shipping_address_placeholder': 'Shipping Address',
    'checkout.mtn_momo': 'MTN MOMO',
    'checkout.pay_on_delivery': 'Pay on Delivery',
    'checkout.momo_payment_code': 'MoMo Payment Code',
    'checkout.momo_instructions': 'Use this number to complete your MoMo payment',
    'checkout.order_success': 'Order placed successfully! Check your email for confirmation.',
    'checkout.pay_on_delivery_notice': 'Your order will be delivered to your address. Payment including delivery fee will be collected upon delivery.',
    'checkout.secure_payment': 'Secure Payment',
    'checkout.encryption_notice': 'Your purchases are secured by industry-standard encryption',
    'checkout.complete_order': 'Complete Order →',
    'checkout.processing': 'Processing...',
    'checkout.order_completed': 'Order Completed ✓',
    'checkout.order_completed_notice': '✅ Order Completed!',
    
    // Community Chat
    'community.chat': 'Community Chat',

    
    // Customers
    'customers.user_management': 'User Management',
    'customers.search_users': 'Search users...',
    'customers.total_buyers': 'Total Buyers',
    'customers.total_sellers': 'Total Sellers',
    'customers.all_users': 'All Users',
    'customers.user': 'User',
    'customers.loading_users': 'Loading users...',
    'customers.failed_load_users': 'Failed to load users',
    'customers.active': 'Active',
  },
  rw: {
     "sellerRequest.review_submitted": "Isuzuma ryatanzwe",
  "sellerRequest.thank_you_review": "Murakoze ku isuzuma ryanyu!",
  "sellerRequest.failed_to_submit_review": "Ntibyashobotse gutanga isuzuma",
  "sellerRequest.error": "Ikosa",
  "sellerRequest.write_comment_review": "Nyamuneka andika igitekerezo ku isuzuma ryawe",
  "sellerRequest.login_to_submit_review": "Ugomba kwinjira mu rubuga kugira ngo utange isuzuma",
  "sellerRequest.loading_reviews": "Kureba isuzuma birimo...",
  "sellerRequest.failed_to_load_reviews": "Ntibyashobotse gupakira isuzuma",
  "sellerRequest.customer_reviews": "Isuzuma ry’Abakiriya",
  "sellerRequest.write_review": "Andika Isuzuma",
  "sellerRequest.write_your_review": "Andika Isuzuma ryawe",
  "sellerRequest.rating": "Icyiciro",
  "sellerRequest.comment": "Igitekerezo",
  "sellerRequest.share_experience": "Sangira uburambe bwawe kuri iki gicuruzwa...",
  "sellerRequest.submitting": "Birimo gutangwa...",
  "sellerRequest.submit_review": "Tanga Isuzuma",
  "sellerRequest.cancel": "Hagarika",
  "sellerRequest.login_to_write_review": "Nyamuneka {loginLink} kugira ngo wandike isuzuma.",
  "sellerRequest.no_reviews_yet": "Nta suzuma rirahari. Ba uwa mbere usuzuma iki gicuruzwa!",
    "common.home": "Ahabanza",
  "common.shop": "Ububiko",
  "products.product_details": "Ibisobanuro by'ibicuruzwa",
  "products.rating_reviews": "Ibyerekeye amanota n'ibitekerezo",
  "products.faqs": "Ibibazo bikunze kubazwa",
    "sellerRequest.search_placeholder": "Shakisha abakiriya ukoresheje amazina cyangwa email...",
  "sellerRequest.registration_date": "Itariki y'iyandikishwa",
  "sellerRequest.all_dates": "Amatariki yose",
  "sellerRequest.today": "Uyu munsi",
  "sellerRequest.this_week": "Icyumweru gishize",
  "sellerRequest.this_month": "Uyu kwezi",
  "sellerRequest.this_year": "Uyu mwaka",
  "sellerRequest.number_of_orders": "Umubare w'ibyo wasabye",
  "sellerRequest.all_orders": "Ibyo wasabye byose",
  "sellerRequest.no_orders": "Nta byo wasabye",
  "sellerRequest.orders_1_5": "Ibyo wasabye 1-5",
  "sellerRequest.orders_6_20": "Ibyo wasabye 6-20",
  "sellerRequest.orders_20_plus": "Ibirenze 20",
  "sellerRequest.activity": "Ibikorwa",
  "sellerRequest.all_activity": "Ibikorwa byose",
  "sellerRequest.recently_active": "Bakoze vuba aha",
  "sellerRequest.inactive": "Ntibakoraga",
  "sellerRequest.clear_all": "Siba byose",
  "vendor_dashboard.title": "Igenamiterere y’Uwucuruza",
  "vendor_dashboard.add_product": "Ongeramo Igicuruzwa",
  "vendor_dashboard.create_order": "Gutumiza",
  "vendor_dashboard.view_all": "Reba Byose",
  "vendor_dashboard.total_orders": "Ibyatumijwe  byose",
  "vendor_dashboard.total_revenue": "Amafaranga yose yinjijwe",
  "vendor_dashboard.total_customers": "Abakiriya bose",
  "vendor_dashboard.total_products": "Ibicuruzwa byose",
  "vendor_dashboard.loading": "Birimo kwinjira...",
  "vendor_dashboard.loading_products": "Birimo kwinjiza ibicuruzwa...",
  "vendor_dashboard.no_products": "Nta bicuruzwa bibonetse.",
  "vendor_dashboard.create_first_product": "Tangira urekure igicuruzwa cyawe cya mbere",
  "vendor_dashboard.revenue_overview": "Isuzuma ry’Inyungu",
  "vendor_dashboard.avg_order_value": "Igiterany cya agaciro kibyatumijwe",
  "vendor_dashboard.no_orders": "Nta byatumijwe bibonetse ku bicuruzwa byawe",
  "vendor_dashboard.loading_orders": "Birimo kwinjiza Ibyatumijwe ...",
  "vendor_dashboard.loading_customers": "Birimo kwinjiza abakiriya...",
  "vendor_dashboard.no_customers": "Nta bakiriya babonetse",
  "vendor_dashboard.recent_orders": "Ibyatumijwe  biheruka",
  "vendor_dashboard.order_id": "Nimero Iranga Ibyatumijwe",
  "vendor_dashboard.customer": "Umukiriya",
  "vendor_dashboard.products": "Ibicuruzwa",
  "vendor_dashboard.date": "Itariki",
  "vendor_dashboard.total": "Igiteranyo",
  "vendor_dashboard.status": "Imiterere",
  "vendor_dashboard.paid": "Byishyuye",
  "vendor_dashboard.pending": "Bitegereje kwishyurwa",
  "vendor_dashboard.recent_customers": "Abakiriya biheruka",
  "vendor_dashboard.unknown": "Ntazina",
  "vendor_dashboard.no_email": "Nta email",
  "vendor_dashboard.orders_count": "Ibyatumijwe ",
  "vendor_dashboard.joined": "Yatangiye",
  "vendor_dashboard.my_products": "Ibicuruzwa Byanjye",  
    "admin_filters.search_placeholder": "Shakisha izina ry'igicuruzwa cyangwa ibisobanuro...",
  "admin_filters.category": "Icyiciro",
  "admin_filters.all_categories": "Ibyiciro Byose",
  "admin_filters.stock": "Ububiko",
  "admin_filters.all_stock": "Ububiko Bwose",
  "admin_filters.in_stock": "Biri mu bubiko",
  "admin_filters.low_stock": "Ububiko buri hasi (<10)",
  "admin_filters.out_of_stock": "Ntibiri mu bubiko",
  "admin_filters.price_range": "Urugero rw'ibiciro",
  "admin_filters.all_prices": "Ibiciro Byose",
  "admin_filters.price_under_10000": "Hasi ya 10,000 Rwf",
  "admin_filters.price_between_10000_50000": "10,000 - 50,000 Rwf",
  "admin_filters.price_above_50000": "Hejuru ya 50,000 Rwf",
  "admin_filters.clear_all": "Siba byose",
     "seller_filter.search_by_name": "Shakisha ibicuruzwa byanjye ukoresheje izina...",
  "seller_filter.category": "Icyiciro",
  "seller_filter.all_categories": "Ibyiciro Byose",
  "seller_filter.stock_level": "Urwego rw'ibicuruzwa bihari",
  "seller_filter.all_stock": "Ibicuruzwa Byose",
  "seller_filter.in_stock": "Bihari (1+)",
  "seller_filter.low_stock": "Biri hasi (<10)",
  "seller_filter.critical_stock": "Igihe cy'amage (<5)",
  "seller_filter.out_of_stock": "Byarashize (0)",
  "seller_filter.performance": "Imikorere",
  "seller_filter.all_performance": "Imikorere Yose",
  "seller_filter.best_selling": "Ibicuruzwa bigurishwa cyane",
  "seller_filter.needs_attention": "Bisaba kwitabwaho",
  "seller_filter.new_products": "Ibicuruzwa bishya",
  "seller_filter.clear_all": "Siba byose",
    "seller.name": "Izina ry'ibicuruzwa *",
  "seller.category": "Icyiciro *",
  "seller.select_category": "Hitamo icyiciro",
  "seller.price": "Igiciro (Frw) *",
  "seller.stock": "Umubare uboneka *",
  "seller.assign": "Hitiramo umucuruzi (Si ngombwa)",
  "seller.select_seller": "Hitamo umucuruzi (ureke ubusa niba ari wowe)",
  "seller.assign_self": "Nshyiraho njye ubwanjye",
  "seller.description": "Ibisobanuro",
  "seller.image_label": "Ifoto y'igicuruzwa",
  "seller.upload_image": "Ohereza ifoto y'igicuruzwa *",
  "seller.or_use_url": "Cyangwa ukoreshe URL *",
  "seller.enter_image_url": "Andika URL y'ifoto",
  "seller.available_colors": "Amabara aboneka",
  "seller.add_color": "Ongeramo ibara",
  "seller.available_sizes": "Ingano ziboneka",
  "seller.add_size": "Ongeramo ingano",
  "seller.add": "Ongeraho",
  "seller.cancel": "Hagarika",
  "seller.processing": "Birimo gutunganywa...",
  "seller.update_product": "Hindura igicuruzwa",
  "seller.create_product": "Kora igicuruzwa gishya",
  "admin.products.title": "Ibicuruzwa Byose",
  "admin.products.my_products": "Ibicuruzwa Byanjye",
  "admin.products.add_product": "Ongeramo Igicuruzwa",
  "admin.products.edit_product": "Hindura Igicuruzwa",
  "admin.products.success": "Byagenze Neza",
  "admin.products.error": "Ikibazo Cyabaye",
  "admin.products.product_created": "Igicuruzwa cyongewe neza!",
  "admin.products.product_updated": "Igicuruzwa cyahinduwe neza!",
  "admin.products.product_deleted": "Igicuruzwa cyasibwe neza!",
  "admin.products.create_failed": "Ntibyashobotse kongeramo igicuruzwa",
  "admin.products.update_failed": "Ntibyashobotse guhindura igicuruzwa",
  "admin.products.delete_failed": "Ntibyashobotse gusiba igicuruzwa",
  "admin.products.confirm_delete": "Urabyizeye ko ushaka gusiba iki gicuruzwa?",
     "chat.community_chat": "Ikiganiro rusange",
  "chat.messages": "ubutumwa",
  "chat.vendors_and_admins": "Abacuruzi n’Abayobozi",
  "chat.no_messages_yet": "Nta butumwa burahari. Tangira kuganira!",
  "chat.failed_load": "Ntibyakunze gupakurura ikiganiro",
  "chat.failed_send_message": "Ntibyakunze kohereza ubutumwa",
  "chat.type_message_placeholder": "Andika ubutumwa...",
  "chat.characters": "inyuguti",
    "customers": {
    "loading_users": "Kurinda abakoresha...",
    "failed_load_users": "Ntibashoboye kubona abakoresha.",
    "user_management": "Imicungire y’Abakoresha",
    "search_users": "Shaka abakoresha...",
    "total_buyers": "Abaguzi bose",
    "total_sellers": "Abacuruzi bose",
    "total_users": "Abakoresha bose",
    "all_users": "Abakoresha bose",
    "user": "Umukoresha",
    "email": "Imeyili",
    "status": "Imiterere",
    "joined": "Yatangiye",
    "active": "Akora",
    "inactive": "Ntakora",
    "failed_to_update": "Ntibishobotse kuvugurura umukoresha"
  },
  "vendors": {
    "admin": "Umuyobozi",
    "seller": "Umucuruzi",
    "buyer": "Umuguzi"
  },
    "customer_management.title": "Imicungire y’Abakiriya ({{count}})",
  "customer_management.customer": "Umukiriya",
  "customer_management.contact": "Uburyo bwo Kuvugana",
  "customer_management.orders": "Ibicuruzwa Yaguze",
  "customer_management.joined": "Yatangiye",
  "customer_management.actions": "Ibikorwa",
  "customer_management.id_prefix": "Indangamuntu",
  "customer_management.orders_label": "ibicuruzwa",
  "customer_management.no_customers": "Nta bakiriya babonetse",
  "customer_management.no_customers_subtext": "Abakiriya bazahita bagaragara hano igihe baguze ibicuruzwa byawe",
  "customer_management.success": "Byagenze neza",
  "customer_management.customer_updated": "Umukiriya yavuguruwe neza",
  "customer_management.error": "Ikosa",
  "customer_management.update_failed": "Ntibyashobotse kuvugurura umukiriya",
  "customer_management.customer_removed": "Umukiriya yakuwemo neza",
  "customer_management.remove_failed": "Ntibyashobotse gukuramo umukiriya",
  "customer_management.confirm_delete": "Urabizi neza ko ushaka gukuramo uyu mukiriya? Ibi ntibizakuraho konti ye, ahubwo bizamukuraho mu rutonde rw’abakiriya bawe.",
  "customer_management.loading_customers": "Kureba abakiriya...",
  "customer_management.edit_customer": "Hindura Umukiriya",
  "customer_management.name": "Amazina",
  "customer_management.email": "Imeyili",
  "customer_management.phone": "Telefone",
  "customer_management.address": "Aderesi",
  "customer_management.cancel": "Hagarika",
  "customer_management.updating": "Birimo kuvugururwa...",
  "customer_management.update_customer": "Vugurura Umukiriya",
     'customers.title': 'abakiriya',
    "seller_customers.failed_load_customers": "Ntibishobotse gupakira abakiliya",
  "seller_customers.my_customers": "Abakiliya banjye",
  "seller_customers.total_customers": "Rusange: abakiliya {{count}}",
  "seller_customers.total_customers_label": "Abakiliya bose",
  "seller_customers.total_orders_label": "Ibicuruzwa byose",
  "seller_customers.new_this_month_label": "Bashya muri uku kwezi",
    "seller_permissions.manage_seller_permissions": "Genzura Uburenganzira bw’Umucuruzi",
  "seller_permissions.permissions_updated_title": "Uburenganzira bwahinduwe",
  "seller_permissions.permissions_updated_description": "Uburenganzira bw’umucuruzi bwahinduwe neza",
  "seller_permissions.error_title": "Ikosa",
  "seller_permissions.error_description": "Ntibyashobotse guhindura uburenganzira",
  "seller_permissions.status.active": "Akora",
  "seller_permissions.status.inactive": "Ntakore",
  "seller_permissions.business": "Ubucuruzi",
  "seller_permissions.order_management_permissions": "Uburenganzira bwo gucunga Ibyerekeye Itegeko",
  "seller_permissions.confirm_orders": "Emeza Itegeko",
  "seller_permissions.allow_confirm_payment": "Reka umucuruzi yemeze niba amafaranga yishyuwe",
  "seller_permissions.edit_orders": "Hindura Itegeko",
  "seller_permissions.allow_edit_order": "Reka umucuruzi ahindure ibisobanuro by’itegeko",
  "seller_permissions.cancel_orders": "Siba Itegeko",
  "seller_permissions.allow_cancel_order": "Reka umucuruzi asibe amategeko",
  "seller_permissions.delete_orders": "Kuraho Itegeko burundu",
  "seller_permissions.allow_delete_order": "Reka umucuruzi akureho amategeko burundu",
  "seller_permissions.customer_management_permissions": "Uburenganzira bwo gucunga abakiriya",
  "seller_permissions.create_customers": "Ongeramo abakiriya bashya",
  "seller_permissions.allow_add_customers": "Reka umucuruzi yongeremo abakiriya bashya igihe acuruza",
  "seller_permissions.cancel": "Hagarika",
  "seller_permissions.saving": "Birimo kubikwa...",
  "seller_permissions.save_permissions": "Bika Uburenganzira",
  "common.success": "Byagenze neza",
  "common.error": "Habaye ikibazo",
  "common.creating": "Birimo gukorwa...",
  "common.cancel": "Hagarika",

  "seller_management.heading": "Imicungire y’Abacuruzi",
  "seller_management.add_button": "Ongeramo Umucuruzi",
  "seller_management.new_seller": "Umucuruzi Mushya",
  "seller_management.name_required": "Izina rirakenewe",
  "seller_management.label_name": "Izina ryuzuye",
  "seller_management.placeholder_name": "John Doe",
  "seller_management.email_required": "Imeyili irakenewe",
  "seller_management.email_invalid": "Imeyili ntago Ariyo",
  "seller_management.label_email": "Aderesi ya Imeyili",
  "seller_management.password_required": "Ijambo ry’ibanga rirakenewe",
  "seller_management.password_min_length": "Nibura inyuguti 6",
  "seller_management.label_password": "Ijambo ry’ibanga",
  "seller_management.create": "Kora Umucuruzi",
  "seller_management.created_success": "Umucuruzi yashyizweho neza",
  "seller_management.create_error": "Ntibyashobotse gushyiraho umucuruzi",
  "seller_management.status_updated": "Imiterere y’umucuruzi yahinduwe",
  "seller_management.status_update_error": "Habaye ikibazo mu guhindura imiterere y’umucuruzi",
  "seller_management.load_error": "Ntibyashobotse gupakira abacuruzi",

  "seller_management.count_all": "Abacuruzi Bose",
  "seller_management.count_active": "Abakora",
  "seller_management.count_pending": "Bategereje",
  "seller_management.count_suspended": "Bahagaritswe",
  "seller_management.active_filter": "Birakora",

  "seller_management.search_placeholder": "Shakisha abacuruzi...",

  "seller_management.all_sellers": "Abacuruzi Bose",

  "seller_management.col_seller": "Umucuruzi",
  "seller_management.col_business": "Ubucuruzi",
  "seller_management.col_contact": "Itumanaho",
  "seller_management.col_status": "Imiterere",
  "seller_management.col_joined": "Yinjiye",
  "seller_management.col_actions": "Ibikorwa",

  "seller_management.status_active": "Akora",
  "seller_management.status_suspended": "Yahagaritswe",
  "seller_management.status_pending": "Bategereje",
  "seller_management.status_inactive": "Ntakorera",

  "seller_management.approve": "Emeza",
  "seller_management.suspend": "Hagarika",
  "seller_management.permissions": "Uburenganzira",
  "seller_management.reactivate": "Subizaho",

  "seller_management.no_results_search": "Nta mucuruzi uboneka ujyanye na \"{{term}}\"",
  "seller_management.no_results": "Nta mucuruzi wabonetse",
     "user_filters.search_placeholder": "Shakisha abakoresha ukoresheje izina, imeyili cyangwa telefoni...",
  "user_filters.status": "Imiterere",
  "user_filters.all_status": "Imiterere yose",
  "user_filters.active": "Akora",
  "user_filters.inactive": "Ntabwo akora",
  "user_filters.blocked": "Yafunzwe",
  "user_filters.role": "Uruhare",
  "user_filters.all_roles": "Uruhare rwose",
  "user_filters.buyers": "Abaguzi",
  "user_filters.sellers": "Abacuruzi",
  "user_filters.admins": "Abayobozi",
  "user_filters.registered": "Iyandikishijwe",
  "user_filters.all_dates": "Igihe cyose",
  "user_filters.today": "Uyu munsi",
  "user_filters.this_week": "Icyumweru",
  "user_filters.this_month": "Uku kwezi",
  "user_filters.this_year": "Uyu mwaka",
  "user_filters.clear_all": "Siba byose",
  "seller_request.back_to_home": "Subira ku rubuga rw’itangiriro",
  "seller_request.become_seller": "Baba umucuruzi",
  "seller_request.have_account": "Ufite konti isanzwe?",
  "seller_request.full_name": "Amazina yawe",
  "seller_request.phone": "Numero ya telefone",
  "seller_request.email": "Imeyili",
  "seller_request.business_name": "Izina ry’ubucuruzi",
  "seller_request.gender": "Igitsina",
  "seller_request.male": "Gabo",
  "seller_request.female": "Gore",
  "seller_request.other": "Ikindi",
  "seller_request.prefer_not": "Ntabwo nshaka kubivuga",
  "seller_request.password": "Ijambobanga",
  "seller_request.agree_text": "Ndasomye kandi nemeye",
  "seller_request.terms": "Amabwiriza n’Amategeko",
  "seller_request.submit": "Ohereza ubusabe",
  "seller_request.submitting": "Birimo koherezwa...",
  "seller_request.error": "Ikosa",
  "seller_request.accept_terms": "Nyamuneka emera amabwiriza n’amategeko",
  "seller_request.success_title": "Byakunze!",
  "seller_request.success_message": "Ubusabe bwawe bwo kuba umucuruzi bwoherejwe neza. Uzabimenyeshwa n'umuyobozi nibimara kwemezwa.",
  "seller_request.redirect_message": "Nyamuneka winjire ukoresheje imyirondoro yawe nibimara kwemezwa.",
  "seller_request.request_submitted": "Ubusabe bwoherejwe!",
  "seller_request.await_email": "Ubusabe bwawe bwo kuba umucuruzi bwoherejwe neza. Uzabona ubutumwa kuri email nyuma yo kwemezwa n’umuyobozi.",
  "seller_request.redirecting_login": "Ugiye koherezwa ku rupapuro rwo kwinjira...",
  "seller_request.submit_failed": "Kohereza ubusabe bwo kuba umucuruzi byanze",
    'Personal.Information':'amakuri kuyikoresha',
    'Full.Name':'Amazina Yose',
    'Email':'Imeri',
    'Phone':'Nimero Yawe',
    'Address':'Aderesi',
    'Business.Information':'amakuri kuri buzinesi',
    'Business.Name':'Izina Rya Buzinesi',
    'Business.Category':'Itsinda ryitsinda',
    'Business.Location':'Amerekezo ya Buzinesi',
    'Success':'byakunze',
    'Profile.updated.successfully':'byakunze wahinduye porofile',
    'Failed.to.update.profile':'byanze guhinduka kuri porofile',
    'Business.Website':'murandasi ya buzinesi',
    'Business.Description':'amakuru ya buzinesi',
    'Updating...':'guhinura...',
    'Update.Profile':'guhindura profile',
    'Account.Details':'Amakuru ya konti',
    'Role':'uruhare',
    'Business':'Ubucuruzi',
    'Location':'Amerekezo',
    'Back to Home':'gusubira kuri home',
    
    // >>>
    'Search.products':'Shakisha ibicurizwa',
    'Category':'Amatsinda',
    'All.Categories':'Amatsinda yose',
    'Price.Range':'Ibiciro',
    'Min':'Ntarengwa',
    'Max':'Ntarengwa',
    'Apply.Price':'Shyiraho Ibiciro',
    'Created.Date':'Italiki byakoreweho',
    'All.Dates':'Amatariki yose',
    'Today':'Uyu Munsi',
    'This.Week':'Iki nicyumweru',
    'This.Month':'Uku kwezi',
    'Custom.Range':'range iyariyose',
    'Apply.Range':'hitamo range',
    'Clear.All':'Siba byose',
    // Navigation
    'nav.home': 'Ahabanza',
    'checkout.location': 'Aho uherereye',
    'checkout.required_fields_note':'Ibice byose by\'ingenzi bigomba kuzuza',
    'checkout.state_province': 'Intara / Umujyi',
    'checkout.country': 'Igihugu',
    'checkout.same_as_customer_address': 'Bisa n\'aho umukiriya ari',
    'checkout.momo_payment_instructions': 'Koresha Iyo Nimero kugirango wuzuze ubwishyu bwa MoMo',
     'checkout.last_name':'andi mazina',
     'checkout.customer_information':'Amakuru kumukiriya',
    'checkout.security_notice': 'Ibicuruzwa byawe birinzwe n\'uburyo bwo kubika amakuru bwemewe n\'inganda',
    'nav.products': 'Ibicuruzwa',
    'Error':'Ikosa',
    'Please.fill':'uzuza ibyo ukwiye kuzuza byose',
    'Email.confirmation':'uzuza imeri kugirango tubona uko tuguha imeri',
    'checkout.continue_shopping':'komeza uhahe',
    'checkout.first_name':'izina ryumuryango',
    'Checkout.last_name':'andi mazina',
    'checkout.email':'imeri',
    'checkout.email_required':'imeri irakenewe',
    'checkout.phone_number':'nimero yawe',
    'checkout.street_line':'nimero yumuhanda',
    'checkout.billing_address':'aderesi yo kwishyuriraho',
    'checkout.city':'umujyi',
    'checkout.postal_code':'code yiposita',
    'checkout.shipping_address':'aderesi bazabyoherezaho',
    'checkout.payment_method':'uburyo bwo kwishyura',
    'checkout.pay_on_delivery':'kwishyura bikugezaho',
    'checkout.momo_payment_code':'nimero yo kwishyuriraho',
    'checkout.order_placed_success':'order yoherejwe byakunze',
    'checkout.pay_on_delivery_description':'Uri shyura amfaranga ibyo waguze babikugejejeho hiyongereyeho amafaranga yo kubizana ',
    'Order.Completed!':'baytumijwe!',
    'placed.successfully':'byakunze order yoherejwe',
    'order.status.':'ibyatumijwe',
    'Continue.Shopping':'komeza Uhahe',
    'Order.Summary':'ibyatumijwe munshamake',
    'Subtotal':'Igiteranyo',
    'Discount':'igabanyirizwa',
    'Delivery.Fee':'igiciro kubyoherjwe',
    'Total':'igiteranyo',
    'delivery.fee.delivery':'amafarang yo kwishyura mubyatumijwe',
    'Total.Orders': 'Ibicuruzwa byose',
    'checkout.order_completed':'byatumijwe',
    'checkout.processing':'birigutumizwa',
    'checkout.complete_order':'bitumize',
    'checkout.secure_payment':'umutekano kunyishyu',
    'Sales.Overview':' Isesengura ry\'Ubucuruzi',
    'Order.Issues':'ibibazo mubyatumijwe',
    'Authentication.Issues':'ibibazo mugukora konti',
    'Email.Issues':'Ibibazo muri imeri',
    'Cart.Issues':'ibibazo mu gitebo',
    'Chart.Issues':'ibibaz kuri cati',
    'My.Sales.Overview':' Isesengura ry\'Ubucuruzi bwanjye',
    'Total.Revenue':'agaciro kabyose',
    'My.Orders': 'Ibicuruzwa byanjye',
    'Order.Analytics': 'Isesengura ry\'Ibicuruzwa',
    'My.Products': 'Ibicuruzwa byanjye',
    'Product.Analytics': 'Isesengura',
    'nav.categories': 'Amatsinda',
    'Monthly.Revenue': 'Umusaruro w\'Ukwezi',
    'Failed.Actions.Dashboard':'ibikorwa bitakozwe neza',
    'nav.about': 'Ibyerekeye',
    'Loading.reports': 'Birimo gutangira raporo',
    'Reports.Analytics': 'Raporo z\'Isesengura',
    'Vendor.Issues':'ibibazi ku bacuruzi',
    'Customer.Analytics': 'Isesengura ry\'Abakiriya',
    'My.Business.Summary':' Isesengura ry\'Ubucuruzi bwanjye',
    'Database.Summary': 'Isesengura ry\'Ikarita y\'Ubucuruzi',
    'Sign.Up': 'Iyandikishe',
    'Vendor.Performance': 'Imikorere y\'Abacuruzi',
    'nav.contact': 'Twandikire',
    'nav.dashboard': 'Ubuyobozi',
    'forget': 'Wibagiwe ijambo ry\'ibanga?',
    'nav.sellers': 'Abacuruzi',
    'Add.Seller':'umucuruzi',
    'Next': 'Icyakurikiraho',
    'Previous': 'Icyabanje',
    'Available:': 'Birahari:',
    'clear.all': 'Siba byose',
    'Try.adjusting': 'Gerageza guhindura gushakisha cyangwa ibipimo byo gutoranya',
    'No.product': 'Nta bicuruzwa biboneka',
    'search': 'Shakisha',
    'Showing': 'Kwerekana',
    'category.search': 'Itsinda',
    'Discover.our': 'Sobanukirwa n\'ibicuruzwa byacu byiza',
    // Common
    
    'common.loading': 'Birimo gutangira...',
    'common.welcome': 'Murakaza neza',
    'common.save': 'Bika',
    'common.delete': 'Gusiba',
    'common.edit': 'Guhindura',
    'common.add': 'Kongeramo',
    'user_management.all_users': 'Ubuyobozi bw\'Abakoresha',
    'user_management.search_users': 'Shakisha abakoresha...',
    'user_management.total_buyers': 'Abakoresha bose',
    'user_management.total_sellers': 'Abacuruzi bose',
    'user_management.email': 'imeri',
    'user_management.role': 'Uruhare',
    'user_management.no_users': 'Nta bakoresha baboneka',
    'user_management.active': 'Bariho',
    'user_management.inactive': 'Ntibariho',
    'user_management.create_user': 'Kora Umukoresha',
    'user_management.update_user': 'Hindura Umukoresha',
    'user_management.title': 'Ubuyobozi bw\'Abakoresha',
    'user_management.status': 'Imiterere',
    'New.Seller': 'Umucuruzi Mushya',
    'user_management.actions': 'Ibikorwa',
    'user_management.user': 'Umukoresha',
    'All.Sellers': 'Abacuruzi Bose',
    'user_management.joined': 'Yinjiye',
    'products.care_instructions_title': 'Amabwiriza yo Kwita ku Bicruzwa',
    'products.out_of_stock': 'Byarangiye',
    'products.in_stock': 'Ibihari',
    'products.color': 'Ibara',
    'products.size': 'Ingano',
    'common.search': 'Gushaka',
    'common.filter': 'Gutoranya',
    'common.clear': 'Gusiba',
    'common.submit': 'Kohereza',
    'common.close': 'Gufunga',
    'common.open': 'Gufungura',
    'common.view': 'Kureba',
    
    // Authentication
    'auth.login': 'Injira',
    'auth.register': 'Kwiyandikisha',
    'auth.logout': 'Gusohoka',
    'auth.email': 'Imeli',
    'auth.password': 'Ijambo ry\'ibanga',
    'auth.name': 'Izina',
    'auth.login_required': 'Ugomba Kwinjira',
    'auth.login_to_add_cart': 'Nyamuneka winjire kugira ngo wongeremo ibicuruzwa mu gitebo',
    'auth.forgot_password': 'Wibagiwe ijambo ry\'ibanga?',
    'auth.remember_me': 'Nyibuke',
    'auth.dont_have_account': 'Ntufite konti?',
    'auth.already_have_account': 'Usanzwe ufite konti?',
    'auth.sign_up': 'Iyandikishe',
    'auth.sign_in': 'Injira',
    'auth.user_found': 'Ukoresha wasanzwe!',
    'auth.user_not_found': 'Ukoresha ntabawo',
    'auth.no_account_found': 'Nta konti iboneka kuri iyi email',
    'auth.verification_code_sent': 'Kode yo kwemeza yoherejwe kuri email yawe',
    'auth.enter_email_check': 'Andika email yawe kugira ngo turebe niba konti ihari',
    'auth.enter_verification_code': 'Andika kode yo kwemeza yoherejwe kuri email yawe',
    'auth.account_verified': 'Konti yemejwe! Kanda hasi kugira ngo uhindure ijambo ryibanga',
    'user_management.loading_users': 'Birimo gutangira abakoresha...',
    'user_management.create_new_user': 'Kora Umukoresha Mushya',
    'user_management.edit_user': 'Hindura Umukoresha',

    'auth.verification_code': 'Kode yo Kwemeza',
    'auth.enter_code': 'Andika kode y\'imibare 6',
    'auth.verify_code': 'Emeza Kode',
    'auth.verifying': 'Birimo kwemeza...',
    'auth.checking': 'Birimo gusuzuma...',
    'auth.check_email': 'Suzuma Email',
    'auth.enter_email': 'Andika email yawe',
    'auth.account_found': 'Konti Yasanze',
    'auth.reset_password': 'Subiza Ijambo ryibanga',
    'auth.code_verified': 'Kode yemejwe!',
    'auth.can_reset_password': 'Ubu ushobora guhindura ijambo ryibanga',
    'auth.invalid_code': 'Kode itari yo',
    'auth.code_incorrect': 'Kode yo kwemeza ntari nziza cyangwa yarangiye',
    'auth.failed_check_user': 'Byanze gusuzuma ukoresha',
    'auth.failed_verify_code': 'Byanze kwemeza kode',
    'common.back': 'Subira inyuma',
    'products.all': 'Ibicuruzwa Byose',
    'products.no_products': 'Nta bicuruzwa biboneka',
    'products.search': 'Shakisha ibicuruzwa...',
    'products.filter': 'Gutoranya',
    'products.clear_filters': 'Siba Gutoranya',
    'products.view_details': 'Reba Ibisobanuro',
    'products.view_cart': 'Reba Gitebo',
    'products.checkout': 'Gukora Icyemezo',
    "Chat.Issues": "Ibibazo by'ibiganiro",
    "Failed/Unfinished.Orders": "Amabwiriza yananiwe cyangwa atarangiye",
    "Refresh": "Ongera usubize",
    "No failed orders found": "Nta mabwiriza yananiwe yabonetse",
    "orders.pending": "arategereje",
    "loading.failed_orders": "Birimo gutangira amabwiriza yananiwe...",
     'products.available': 'Ibicuruzwa biboneka',
      'review.add_review_for': 'Ongeraho isuzuma kuri',
      'review.rating': "Urusobe rw'amanota",
      'review.comment': 'Igitekerezo',
      'review.share_experience': 'Sangira uburambe bwawe',
      'review.submit': 'Ohereza',
    
    // Products
    'products.search_placeholder': 'Shakisha ibicuruzwa...',
    'products.no_products_available': 'Nta bicuruzwa bihari ubu.',
    'products.view_more': 'Reba Byinshi',
    'products.loading_related': 'Birimo gutangira ibicuruzwa bifitaniye isano...',
    'products.you_might_like': 'Bishoboka ko ubishaka',
    'products.add_to_cart': 'Shyira mu Gitebo',
    
    // Cart
    'cart.added_to_cart': 'Byashyizwe mu gitebo',
    'cart.item_added': '{{item}} byashyizwe mu gitebo cyawe.',
    'cart.failed_to_add': 'Byanze gushyirwa mu gitebo',
    'cart.add_to_cart': 'Shyira mu Gitebo',
    'cart.adding': 'Birimo gushyirwa...',
    
    // Categories
    'categories.loading': 'Birimo gutangira amatsinda...',
    'categories.no_categories': 'Nta matsinda ahari.',
    'categories.browse_categories': 'SHAKISHA HAKURIKIJWE AMATSINDA',
    'categories.discover_products': 'Menya ibicuruzwa bitandukanye byateguwe hakurikijwe amatsinda',
    'categories.view_all': 'Reba Amatsinda Yose',
    
    // Home
    'home.new_arrivals': 'IBICURUZWA BISHYA',
    'home.top_selling': 'IBICURUZWA BICURUZA CYANE',
    'home.browse_categories': 'Shakisha hakurikijwe Itsinda',
    
    // Hero Section
    'hero.title': 'Murakaza neza ku Isoko Ryubwenge ry\'Abacuruzi b\'Abagore mu Rwanda',
    'hero.description': 'Ryubatswe kubacuruzi b\'abagore bo i Kigali, WomXchange Rwanda itanga urubuga rworoshye rwo gucuruza, gucunga, no kwagura ubucuruzi bwawe.',
    'hero.shop_now': 'Gura Ubu',
    'hero.image_alt': 'Umucuruzi w\'umugore watsindiye',
    
    // Footer
    'footer.company_name': 'WomXchange Rwanda',
    'footer.company_description': 'Gutera imbere abacuruzi b\'abagore bo mu Rwanda hakoreshejwe urubuga rw\'isoko ryubwenge.',
    'footer.location': 'Kigali, u Rwanda',
    'footer.quick_links': 'Ihuza Ryihuse',
    'footer.support': 'Ub ufasha',
    'footer.help_center': 'Ikigo cy\'Ubufasha',
    'footer.shipping_info': 'Amakuru y\'Iyohereza',
    'footer.returns': 'Iyasubizwa',
    'footer.privacy_policy': 'Politiki y\'Ibanga',
    'footer.terms_of_service': 'Amabwiriza y\'Inyago',
    'footer.location_title': 'Ahantu',
    'footer.location_description': 'Sura ibiro byacu i Kigali cyangwa ugure kumurongo uherereye ahantu hose mu Rwanda.',
    'footer.store_hours': 'Amasaha y\'Iduka',
    'footer.weekdays': 'Ku cyumweru - Kw\'igatanu: 9:00 AM - 9:00 PM',
    'footer.weekends': 'Ku cyomboro - Ku cyumweru: 10:00 AM - 9:00 PM',
    'footer.copyright': '© 2024 WomXchange. Uburenganzira bwose burarangiye. Byakozwe n\'urukundo kubacuruzi b\'abagore.',
    "title": "Iyoborwa ry'ibicuruzwa",
    "add_product": "Ongeraho Igicuruzwa",
    "edit_product": "Hindura Igicuruzwa",
    "create_product": "Hanga Igicuruzwa Gishya",
    "created": "Igicuruzwa cyoherejwe neza.",
    "updated": "Igicuruzwa gihinduwe neza.",
    "deleted": "Igicuruzwa cyasibwe neza.",
    "create_failed": "Kunanirwa guhanga igicuruzwa.",
    "update_failed": "Kunanirwa guhindura igicuruzwa.",
    "delete_failed": "Kunanirwa gusiba igicuruzwa.",
    "load_error": "Kunanirwa gupakurura ibicuruzwa.",
    "confirm_delete": "Urashaka koko gusiba iki gicuruzwa?",
    "name": "Izina",
    "description": "Ibisobanuro",
    "price": "Igiciro (Rwf)",
    "stock": "Ubwinshi",
    "image": "Ishusho ya URL",
    "category": "Icyiciro",
    "select_category": "Hitamo icyiciro",
    "create": "Hanga",
    "update": "Hindura",
    "all": "Ibicuruzwa Byose",
    "actions": "Ibikorwa",
    "no_products": "Nta bicuruzwa biboneka",
    
    "Our.Products": "Ibicuruzwa byacu",
    "products": "Ibicuruzwa",
    
    // Admin Categories - Kinyarwanda
    'admin.categories.title': 'Gucunga ibyiciro',
    'admin.categories.add_category': 'Ongeramo icyiciro',
    'admin.categories.create_new': 'Kurema icyiciro gishya',
    'admin.categories.category_name': 'Izina ry\'icyiciro',
    'admin.categories.description': 'Ibisobanuro',
    'admin.categories.creating': 'Gikurema...',
    'admin.categories.create_category': 'Kurema icyiciro',
    'admin.categories.search_categories': 'Shakisha ibyiciro ukurikije izina cyangwa ibisobanuro...',
    'admin.categories.clear': 'Siba',
    'admin.categories.no_categories': 'Nta byiciro byabonetse',
    'admin.categories.no_match_search': 'Nta byiciro bihuje amakuru yawe yo gushakisha',
    'admin.categories.adjust_search': 'Gerageza guhindura amakuru yo gushakisha',
    'admin.categories.name': 'Izina',
    'admin.categories.actions': 'Ibikorwa',
    'admin.categories.edit_category': 'Guhindura icyiciro',
    'admin.categories.updating': 'Gihinduka...',
    'admin.categories.update_category': 'Guhindura icyiciro',
    
    // Orders Management - Kinyarwanda
    'orders.order_management': 'Gucunga ibyatumijwe',
    'orders.create_order': 'Gutumiza',
    'orders.filters_search': 'Gushungura no gushakisha',
    'orders.search_placeholder': 'Shakisha ukurikije ID, izina ry\'umukiriya cyangwa imeli...',
    'orders.status': 'Imiterere',
    'orders.all_orders': 'Ibyatumijwe byose',
    'orders.pending_orders': 'Ibyatumijwe biteheranye',
    'orders.delivered_orders': 'Ibyatumijwe byatanzwe',
    'orders.cancelled_orders': 'Ibyatumijwe byavuyeho',
    'orders.paid_orders': 'Ibyatumijwe byishyuwe',
    'orders.unpaid_orders': 'Ibyatumijwe bitishyuwe',
    'orders.filter_by_date': 'Gushungura ukurikije italiki',
    'orders.all_dates': 'Amatariki yose',
    'orders.today': 'Uyu munsi',
    'orders.last_7_days': 'Iminsi 7 ishize',
    'orders.last_30_days': 'Iminsi 30 ishize',
    'orders.custom_date': 'Urwego rw\'amatariki',
    'orders.start_date': 'Italiki yo gutangira',
    'orders.end_date': 'Italiki yo gurangiza',
    'orders.showing_orders_from': 'Byerekanwe Ibyatumijwe kuva',
    'orders.showing_orders': 'Byerekanwe {{filtered}} muri {{total}} bisabwa',
    'orders.clear_filters': 'Siba amashungura yose',
    'orders.real_time_updates': 'Ivugurura ry\'igihe nyacyo',
    'orders.order_id': 'ID y\'igisabwa',
    'orders.customer': 'Umukiriya',
    'orders.items': 'Ibintu',
    'orders.total': 'Igiteranyo',
    'orders.payment': 'Kwishyura',
    'orders.delivery': 'Gutanga',
    'orders.date': 'Italiki',
    'orders.actions': 'Ibikorwa',
    'orders.confirm_payment': 'Kwemeza kwishyura',
    'orders.cancel_order': 'Kureka igisabwa',
    'orders.delete_order': 'Gusiba igisabwa',
    'orders.view_details': 'Kureba amakuru arambuye',
    'orders.no_orders_found': 'Nta bisabwa byabonetse',
    'orders.no_orders_match_filters': 'Nta bisabwa bihuje amashungura yawe',
    'orders.try_adjusting_filters': 'Gerageza guhindura amashungura cyangwa amakuru yo gushakisha',
    'orders.payment_confirmed': 'Kwishyura byemejwe',
    'orders.payment_confirmed_description': 'Kwishyura kw\'igisabwa #{{orderId}} byemejwe',
    'orders.failed_confirm_payment': 'Byanze kwemeza kwishyura',
    'orders.order_cancelled': 'Igisabwa cyavuyeho',
    'orders.order_cancelled_description': 'Igisabwa #{{orderId}} cyavuyeho',
    'orders.failed_cancel_order': 'Byanze gukuraho igisabwa',
    'orders.order_deleted': 'Igisabwa cyasibwe',
    'orders.order_deleted_description': 'Igisabwa #{{orderId}} cyasibwe',
    'orders.failed_delete_order': 'Byanze gusiba igisabwa',
    
    // Sidebar - Kinyarwanda
    'sidebar.dashboard': 'Ikurikirana',
    'sidebar.customers': 'Abakiriya',
    'sidebar.vendors': 'Abacuruzi',
    'sidebar.products': 'Ibicuruzwa',
    'sidebar.orders': 'Ibyatumijwe',
    'sidebar.reports': 'Raporo',
    'sidebar.analytics': 'Isesengura',
    'sidebar.profile': 'Umwirondoro',
    'sidebar.settings': 'Igenamiterere',
    'sidebar.community_chat': 'Uruganiriro ',
    'sidebar.management': 'Ubuyobozi',
    
    // Admin Pages - Kinyarwanda
    'admin.user': 'Abakoresha',
    'admin.vendors': 'Abacuruzi',
    'admin.products': 'Ibicuruzwa',
    'admin.orders': 'Ibyatumijwe',
    'admin.reports': 'Raporo',
    'admin.analytics': 'ibyiciro',
    'admin.community_chat': 'Iganira ry\'ubunyangamugayo',
    'admin.management': 'Ubuyobozi',
    'admin.sidebar.dashboard': 'Ikurikirana',
    'admin.sidebar.customers': 'Abakiriya',
    'admin.sidebar.vendors': 'Abacuruzi',
    'admin.sidebar.products': 'Ibicuruzwa',
    'admin.sidebar.orders': 'Ibyatumijwe',
    'admin.sidebar.reports': 'Raporo',
    'admin.sidebar.analytics': 'Amatsinda',
    'admin.sidebar.profile': 'Umwirondoro',
    'admin.sidebar.settings': 'Igenamiterere',
    
    // Reports - Kinyarwanda
    'reports.my_sales_reports': 'Raporo z\'icuruza ryanjye n\'isesengura',
    'reports.my_customers': 'Abakiriya banjye',
    'reports.my_sales_overview': 'Incamake y\'icuruza ryanjye',
    'reports.my_products': 'Ibicuruzwa byanjye',
    'reports.my_orders': 'Ibyatumijwe byanjye',
    'reports.my_business_summary': 'Incamake y\'ubucuruzi bwanjye',
    'reports.total_customers': 'Abakiriya bose',
    'reports.paid_orders': 'Ibyatumijwe byishyuwe',
    // Testimonials
    'testimonials.title': 'ABAKIRIYA BACU BISHIMIYE',
    'testimonials.review_1': 'Ibicuruzwa byiza cyane kandi biboherezwa vuba. Ndakunda gushyigikira abacuruzi b\'aho!',
    'testimonials.review_2': 'Ibintu byo kwisiga naguze biratangaje. Ibiciro byiza kandi ibicuruzwa nyabyo kuva kumugore ufite ubuhanga.',
    'categories.browse_by_categories':'Shakisha ugendeye kumatsinda',
    'testimonials.review_3': 'Iri soko ryahinduye ubunyangamugayo bwanjye bwo kugura. Ibintu byinshi bidasanzwe kandi serivisi nziza!',
    'testimonials.no_reviews':"ntacyo baribivugaho",
    'testimonials.review_4': 'Serivisi nziza y\'abakiriya n\'ibicuruzwa byujuje Ibyatumijwe. Nzongera kugura hano!',
    'testimonials.review_5': 'Nkunda ibicuruzwa bitandukanye Kandi birahari. Gushyigikira ubucuruzi bw\'aho ntabwo byigeze nibyiza!',
    'testimonials.be_first_review':'Ba uwambere kugira icyo ubivugaho',
    
    // Banner
    'banner.sell_on_system': 'Gucuruzira kuri sisiteme yacu',
    'banner.join_as_seller': 'Winjire nk\'Umucuruzi',
    
    // Dashboard
    'dashboard.notifications': 'Nta makuru',
    'dashboard.profile': 'Umwirondoro',
    'Don.have':'nta konti ufite',
    'dashboard.settings': 'Igenamiterere',
    
    // Error Pages
    'error.404.title': '404 - Urupapuro Rutabonetse',
    'error.404.message': 'Urupapuro ushaka ntirubaho.',
    'error.404.return_home': 'Subira Ahabanza',
    'error.failed_load_products': 'Byanze gutangira ibicuruzwa',
    
    // Language
    'language.english': 'Icyongereza',
    'language.kinyarwanda': 'Ikinyarwanda',
    
    // Navigation Additional
    'nav.back_to_home': 'Subira Ahabanza',
    
    // Modal and Dialog Messages
    'modal.password_error': 'Ikosa ry\'Ijambo ry\'Ibanga',
    'modal.passwords_not_match': 'Amagambo y\'ibanga ntabwo ahura cyangwa ari ubusa',
    'modal.registration_successful': 'Kwiyandikisha Byakunze!',
    'modal.account_created': 'Konti yashyizweho. Ubu turasubiza iteka ryawe...',
    'modal.registration_failed': 'Kwiyandikisha Byanze',
    'modal.failed_create_account': 'Byanze gukora konti',
    'modal.order_placed_success': 'Iteka Ryashyizwe Neza!',
    'modal.order_confirmation_sent': 'Iteka ryawe ryashyizwe kandi ubutumwa bwo kwemeza bwoherejwe.',
    'modal.order_failed': 'Iteka Ryanze',
    'modal.failed_place_order': 'Byanze gushyira iteka',
    'modal.create_account_optional': 'Kora Konti (Bitegetswe)',
    'modal.place_order': 'Shyira Iteka',
    'modal.create_account_benefits': 'Kora konti kugira ngo ukurikirane Ibyatumijwe byawe kandi ubone amahirwe y\'ihariye, cyangwa usimbuke ugashyira iteka nk\'umushyitsi.',
    'modal.create_account': 'Kora konti',
    'modal.skip_place_order': 'Simbuka & Shyira Iteka',
    'modal.account_created_success': 'Konti yakozwe neza! Ubu turasubiza iteka ryawe...',
    
    // Contact Page Messages
    'contact.message_sent_success': 'Ubutumwa bwawe bwoherejwe neza!',
    'contact.message_send_failed': 'Byanze kohereza ubutumwa. Nyamuneka ongera ugerageze nyuma.',
    'contact.error_occurred': 'Ikosa ryabaye. Nyamuneka ongera ugerageze.',
    
    // Register Page
    'register.back_to_home': 'Subira Ahabanza',
    'register.create_account': 'Kora Konti',
    'register.already_have_account': 'Usanzwe ufite konti?',
    'register.creating_account': 'Birimo gukora konti...',
    
    // Register Page Additional
    'register.registration_successful': 'Kwiyandikisha Byakunze',
    'register.login_with_credentials': 'Nyamuneka winjire ukoresha ibyo washyizeho',
    'register.registration_failed': 'Kwiyandikisha Byanze',
    'register.something_went_wrong': 'Ikintu kitateze neza',
    'register.full_name': 'Izina Ryuzuye',
    'register.enter_full_name': 'Andika izina ryawe ryuzuye',
    'register.email': 'Imeli',
    'register.enter_email': 'Andika imeli yawe',
    'register.password': 'Ijambo ryibanga',
    'register.create_password': 'Kora ijambo ryibanga',
    'register.account_type': 'Ubwoko bwa Konti',
    'register.select_account_type': 'Hitamo ubwoko bwa konti',
    'register.buyer': 'Umuguzi',
    'register.seller': 'Umucuruzi',
    'register.admin': 'Umuyobozi',
    'register.looking_to_sell': 'Urashaka kugurisha ibicuruzwa?',
    'register.start_selling_now': 'Tangira Gucuruza Ubu',
    
    // Chat Interface
    'chat.messages_vendors_admins': 'ubutumwa • Abacuruzi nabayobozi',
    'chat.failed_to_load': 'Byanze gutangira ikiganiro',
    'chat.retry': 'Ongera ugerageze',
    'chat.type_message': 'Andika ubutumwa...',

    // Admin Pages
    'admin.customers': 'Abakiriya',
   
   
    'seller.management': 'Ubuyobozi bw\'Abacuruzi',
    // Customer Management
    'customers.add_customer': 'Kongeramo Umukiriya',
    'customers.search_customers': 'Shakisha abakiriya...',
    'customers.all_customers': 'Abakiriya Bose',
    'customers.active': 'Bakora',
    'customers.inactive': 'Ntibakora',
    'customers.total_customers': 'Abakiriya Bose',
    'customers.customer': 'Umukiriya',
    'customers.email': 'Imeli',
    'customers.joined': 'Yinjiye',
    'customers.status': 'Uko bimeze',
    'customers.actions': 'Ibikorwa',
    'customers.no_customers': 'Nta bakiriya babonetse',
    'customers.import': 'Kwinjiza',
    'customers.export': 'Gusohora',
    
    // Vendor Management
    'vendors.title': 'Ubuyobozi bw\'Abacuruzi',
    'vendors.add_vendor': 'Kongeramo Umucuruzi',
    'vendors.search_vendors': 'Shakisha abacuruzi...',
    'vendors.total_vendors': 'Abacuruzi Bose',
    'vendors.total_users': 'Abakoresha Bose',
    'vendors.vendor': 'Umucuruzi',
    'vendors.role': 'Uruhare',
    'vendors.no_vendors': 'Nta bacuruzi babonetse',
    'vendors.active_sellers': 'Abacuruzi Bakora',
    'vendors.all_registered': 'Abakoresha bose biyandikishije',
    
    // Orders Management
    'orders.title': 'Ubuyobozi bw\'Ibyatumijwe',
    'orders.refresh': 'Vugurura Ibyatumijwe',
    'orders.search_orders': 'Shakisha Ibyatumijwe...',
    'orders.total_orders': 'Ibyatumijwe byose',
    'orders.pending_payment': 'Bitegereje Kwishyura',
    'orders.total_revenue': 'Amafaranga Yose',
    'orders.total_price': 'Igiciro Cyose',
    'orders.payment_status': 'Uko Kwishyura Bimeze',
    'orders.delivery_status': 'Uko Gutanga Bimeze',
    'orders.mark_delivered': 'Shyira Nk\'Ibyatanzwe',
    'orders.no_orders': 'Nta mateka abonetse',
    'orders.confirmed_by_admin': 'Byemejwe n\'Umuyobozi',
    'orders.awaiting_admin': 'Bitegereje Umuyobozi',
    'orders.payment_code_generated': 'Kode y\'Kwishyura Yarakozwe',
    'orders.pending_payment_status': 'Bitegereje Kwishyura',
    'orders.delivered': 'Byatanzwe',
    'orders.not_delivered': 'Ntibyatanzwe',
    
    // User Pages
    'categories.title': 'Gura Hakurikijwe Amatsinda',
    'categories.description': 'Menya amatsinda menshi y\'ibicuruzwa kandi ubone ibyo ushaka neza.',
    'categories.no_categories_found': 'Nta matsinda Abonetse',
    'categories.categories_appear': 'Amatsinda azagaragara hano amaze kongerwa muri sisiteme.',
    
    // Products Page
    'products.title': 'Ibicuruzwa',
    'products.filters': 'Gutoranya',
    'products.category': 'Itsinda',
    'products.price_range': 'Urwego rw\'Igiciro',
    'products.price': 'Ibiciro',
    'products.actions': 'ibikorwa',
    'products.name': 'izina',
    'products.image': 'Ifoto',
    'products.description': 'Ibisobanuro',
    'products.stock': 'Ubwinshi',
    'products.add_product': 'kongera igicuruzwa',
    'products.showing_results': 'Byerekana {{count}} muri {{total}} ibicuruzwa',
    'products.no_products_matching': 'Nta bicuruzwa bihuye n\'amatoranywa yawe.',
    'products.previous': 'Ibyambere',
    'products.next': 'Ibikurikira',
    
    // Cart Page
    'cart.title': 'IGITEBO CYAWE',
    'cart.empty': 'Igitebo cyawe nticyfite kintu',
    'cart.continue_shopping': 'Komeza Kugura',
    'cart.order_summary': 'Incamake y\'Iteka',
    'cart.subtotal': 'Igiteranyo',
    'cart.discount': 'Kugabanuka (-2%)',
    'cart.delivery_fee': 'Amafaranga yo Gutanga',
    'cart.total': 'Byose',
    'cart.go_to_checkout': 'Jya kwishyura',
    'cart.please_login': 'Nyamuneka Winjire',
    'cart.login_to_view': 'Ugomba kwinjira kugira ngo urebe igitebo cyawe.',
    'cart.loading': 'Birimo gutangira igitebo...',
    
    // Checkout Page
    'checkout.title': 'Kwishyura',
    'checkout.billing_info': 'Amakuru yo Kwishyura',
    'checkout.full_name': 'Izina Ryuzuye',
    'checkout.phone': 'Nimero ya Telefoni',
    'checkout.address': 'Aderesi',
    'checkout.mobile_money': 'Mobile Money',
    'checkout.place_order': 'Shyira Iteka',
    'checkout.order_summary': 'Incamake y\'Iteka',

    // Order Complete Page
    'order_complete.title': 'Iteka Ryashyizwe Neza!',
    'order_complete.message': 'Iteka ryawe ryakiriye kandi ririmo gutunganywa.',
    'order_complete.order_id': 'Nimero y\'Iteka: #{{id}}',
    'order_complete.payment_processing': 'Gutunganya Kwishyura',
    'order_complete.generate_code': 'Kora kode yo kwishyura kugira ngo ukomeze na MoMo',
    'order_complete.generate_payment_code': 'Kora Kode yo Kwishyura',
    'order_complete.payment_code': 'Kode Yawe yo Kwishyura:',
    'order_complete.use_code': 'Koresha iyi kode kugira ngo urangize kwishyura kwa MoMo, hanyuma wemeze hepfo',
    'order_complete.made_payment': 'Narishyuye',
    'order_complete.awaiting_confirmation': 'Bitegereje Umuyobozi',
    'order_complete.payment_verification': 'Kwishyura kwawe birimo kwemezwa n\'itsinda ryacu ry\'ubuyobozi',
    'order_complete.view_orders': 'Reba Ibyatumijwe Byanjye',
    'order_complete.return_home': 'Subira Ahabanza',
    'order_complete.secured': 'Ibyo wagize bifashwe n\'ubunyangamugayo bukomeye',
    'order_complete.order_id_not_found': 'Nimero y\'Iteka ntiyabonetse',
    'order_complete.code_generated_success': 'Kode yo kwishyura yakozwe neza',
    'order_complete.failed_generate_code': 'Byanze gukora kode yo kwishyura',
    'order_complete.payment_confirmed': 'Kwishyura byemejwe! Bitegereje kwemezwa n\'umuyobozi.',
    'order_complete.failed_confirm_payment': 'Byanze kwemeza kwishyura',
    
    //Dashboard
    'dashboard.daily_sales': 'Umuzingo wa buri munsi',
    'dashboard.daily_users': 'Uwakoresheje buri munsi',
    'dashboard.summary_sales': 'Incamake y\'umushinga',
    'dashboard.chart_placeholder': 'Ahantu ho kwerekana amashusho',
    'dashboard.upcoming_payments': 'Kwishyura kuri hafi',
    'dashboard.payment_data': 'Amakuru yo kwishyura',
    'dashboard.recent_orders': 'Ibyatumijwe biheruka',
    'dashboard.id': 'nimero',
    'dashboard.customer_name': 'Izina ry\'umukiriya',
    'dashboard.product_name': 'Izina ry\'igicuruzwa',
    'dashboard.price': 'Igiciro',
    'dashboard.picture': 'Ifoto',
    'dashboard.sample_product': 'umwenda',
    'dashboard.expense_status': 'Imiterere y\'ikiguzi',
    'dashboard.vendor_role': 'Umucuruzi',
    'dashboard.retry': 'Gerageza',
    
    // Failed Actions
    'failed_actions.title': 'Gucunga Ibikorwa Byanze',
    'failed_actions.description': 'Gukurikirana no gukemura amakosa ya sisitemu',
    'failed_actions.type': 'Ubwoko',
    'failed_actions.status': 'Imiterere',
    'failed_actions.reason': 'Impamvu',
    'failed_actions.date': 'Itariki',
    'failed_actions.actions': 'Ibikorwa',
    'failed_actions.resend': 'Ongera wohereze',
    'failed_actions.retry': 'Ongera ugerageze',
    'failed_actions.clear': 'Gusiba',
    'failed_actions.resolve': 'Gukemura',
    'failed_actions.failed_email': 'Imeli Yanze',
    'failed_actions.failed_login': 'Kwinjira Byanze',
    'failed_actions.failed_cart': 'Gitebo Cyanze',
    'failed_actions.failed_chat': 'Iganiro Ryanze',
    'failed_actions.failed_vendor': 'Umucuruzi Yanze',
    'failed_actions.failed_order': 'Itumiza Ryanze',
    'failed_actions.no_actions': 'Nta bikorwa byanze biboneka',
    'failed_actions.refreshing': 'Birashya...',
    'failed_actions.loading': 'Birashakisha ibikorwa byanze...',
    
    // Filters
    'filters.search': 'Gushaka',
    'filters.category': 'Icyiciro',
    'filters.date_range': 'Amatariki',
    'filters.price_range': 'Igiciro',
    'filters.stock_range': 'Ibigize',
    'filters.status': 'Imiterere',
    'filters.clear_all': 'Gusiba Byose',
    'filters.apply': 'Gukoresha',
    'filters.start_date': 'Itariki yo Gutangira',
    'filters.end_date': 'Itariki yo Kurangiza',
    'filters.min_price': 'Igiciro Gito',
    'filters.max_price': 'Igiciro Kinini',
    'filters.min_stock': 'Umubare Muto',
    'filters.max_stock': 'Umubare Munini',
    
    // About Page - Kinyarwanda
    'about.our_story': 'Inkuru Yacu',
    'about.story_content': 'Hashyizweho mu mutima wa Kigali, wXc, WomXchange yavutse mu gitekerezo yoroheje ariko gifite imbaraga: gukora isoko rya elegitoronike aho abagore b\'u Rwanda bashobora kwerekana, kugurisha, kandi gukuza ubucuruzi bwabo mu buryo bwabo. Ibyatangiriye mu gitekerezo cy\'umuntu umwe ubu byahindutse umushinga mu bagore b\'abacuruzi kandi byakuze bigabanye ku cyicaro cy\'ubucuruzi cya elegitoronike cya mbere muri Rwanda cyegereye kwihutaza abacuruzi b\'abagore hose muri buri karere ka Kigali.',
    'about.mission': 'Intego',
    'about.mission_content': 'Hashyizweho mu mutima wa Kigali, wXc, WomenXchange yavutse mu gitekerezo yoroheje ariko gifite imbaraga yo gukora isoko rya elegitoronike aho abagore b\'u Rwanda bashobora kwerekana, kugurisha, kandi gukuza ubucuruzi bwabo mu buryo bwabo. Ibyatangiriye mu gitekerezo cy\'umuntu umwe ubu byahindutse umushinga mu bagore b\'abacuruzi kandi byakuze bigabanye ku cyicaro cy\'ubucuruzi cya elegitoronike cya mbere muri Rwanda cyegereye kwihutaza abacuruzi b\'abagore hose muri buri karere ka Kigali.',
    'about.vision': 'Icyerekezo',
    'about.vision_content': 'Hashyizweho mu mutima wa Kigali, wXc, WomenXchange yavutse mu gitekerezo yoroheje ariko gifite imbaraga yo gukora isoko rya elegitoronike aho abagore b\'u Rwanda bashobora kwerekana, kugurisha, kandi gukuza ubucuruzi bwabo mu buryo bwabo. Ibyatangiriye mu gitekerezo cy\'umuntu umwe ubu byahindutse umushinga mu bagore b\'abacuruzi kandi byakuze bigabanye ku cyicaro cy\'ubucuruzi cya elegitoronike cya mbere muri Rwanda cyegereye kwihutaza abacuruzi b\'abagore hose muri buri karere ka Kigali.',
    
    // Dashboard Additional - Kinyarwanda
    'dashboard.total_revenue': 'Amafaranga Yose Yinjiye',
    'dashboard.paid_revenue': 'Amafaranga Yishyuwe',
    'dashboard.total_orders': 'Ibyatumijwe byose',
    'dashboard.total_users': 'Abakoresha Bose',
    'dashboard.products': 'Ibicuruzwa',
    'dashboard.buyers': 'Abaguzi',
    'dashboard.sellers': 'Abacuruzi',
    'dashboard.admins': 'Abayobozi',
    'dashboard.monthly_orders': 'Ibyatumijwe bya Buri Kwezi',
    'dashboard.user_roles_distribution': 'Kugabanya Inshingano z\'Abakoresha',
    'dashboard.monthly_revenue_trend': 'Icyerekezo cy\'Amafaranga ya Buri Kwezi',
    'dashboard.payment_status': 'Imiterere y\'Kwishyura',
    'dashboard.payment_summary': 'Incamake y\'Kwishyura',
    'dashboard.paid_orders': 'Ibyatumijwe Yishyuwe',
    'dashboard.pending': 'Bitegereje',
    'dashboard.order_statistics': 'Imibare y\'Ibyatumijwe',
    'dashboard.pending_orders': 'Ibyatumijwe Ategereje',
    'dashboard.user_statistics': 'Imibare y\'Abakoresha',
    'orders.paid': 'Yishyuwe',
    'orders.processing': 'Birimo gutegurwa',
    
    // Contact Page - Kinyarwanda
    'contact.send_message': 'Twoherereze Ubutumwa',
    'contact.full_name': 'Andika amazina yawe yose',
    'contact.email': 'Andika imeli yawe',
    'contact.message': 'Andika ubutumwa bwawe hano...',
    'contact.send': 'Kohereza',
    'contact.phone': 'Telefoni:',
    'contact.email_label': 'Imeli:',
    'contact.times': 'Igihe:',
    'contact.location': 'Aho tubarizwa:',
    'contact.hours': 'Ku wa mbere - Ku cyumweru: 7:00 - 21:00',
    'contact.address': 'Downtown House Kigali',
    
    // Analytics - Kinyarwanda
    'analytics.title': 'Isesengura',
    'analytics.coming_soon': 'Urupapuro rw\'isesengura ruza vuba...',
    
    // Checkout - Kinyarwanda
    'checkout.back_to_cart': 'Garuka ku Gitebo',
    // 'checkout.title': 'Kwishyura', // Removed    'community.chat': 'Iganiro ry\'Umuryango',
    
    // Customers - Kinyarwanda
    'customers.user_management': 'Gucunga Abakoresha',
    'customers.search_users': 'Shakisha abakoresha...',
    'customers.total_buyers': 'Abaguzi Bose',
    'customers.total_sellers': 'Abacuruzi Bose',
    'customers.all_users': 'Abakoresha Bose',
    'customers.user': 'Ukoresha',
    'customers.loading_users': 'Biratangura abakoresha...',
    'customers.failed_load_users': 'Byanze gutangira abakoresha',
    // 'customers.active': 'Birakora', // Removed duplicate
    // 'customers.inactive': 'Ntibirakora', // Removed duplicate
    'customers.total_users': 'Abakoresha Bose',
  },
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language') as Language;
    return saved || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string, params?: Record<string, any>): string => {
    let translation = translations[language][key] || translations['en'][key] || key;
    
    // Fallback for missing translations
    if (translation === key) {
      console.warn(`Missing translation for key: ${key}`);
      // Return a readable version of the key
      return key.split('.').pop()?.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase()) || key;
    }
    
    if (params) {
      Object.keys(params).forEach(param => {
        translation = translation.replace(`{{${param}}}`, params[param]);
      });
    }
    
    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};